/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.devices.users.types;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_EMPTY)
@JsonDeserialize(
    builder = DeleteUserResponse.Builder.class
)
public final class DeleteUserResponse {
  private final String message;

  private DeleteUserResponse(String message) {
    this.message = message;
  }

  /**
   * @return Feedback on successful user deletion.
   */
  @JsonProperty("message")
  public String getMessage() {
    return message;
  }

  @Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof DeleteUserResponse && equalTo((DeleteUserResponse) other);
  }

  private boolean equalTo(DeleteUserResponse other) {
    return message.equals(other.message);
  }

  @Override
  public int hashCode() {
    return Objects.hash(this.message);
  }

  @Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static MessageStage builder() {
    return new Builder();
  }

  public interface MessageStage {
    _FinalStage message(String message);

    Builder from(DeleteUserResponse other);
  }

  public interface _FinalStage {
    DeleteUserResponse build();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements MessageStage, _FinalStage {
    private String message;

    private Builder() {
    }

    @Override
    public Builder from(DeleteUserResponse other) {
      message(other.getMessage());
      return this;
    }

    /**
     * <p>Feedback on successful user deletion.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @Override
    @JsonSetter("message")
    public _FinalStage message(String message) {
      this.message = message;
      return this;
    }

    @Override
    public DeleteUserResponse build() {
      return new DeleteUserResponse(message);
    }
  }
}
