/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface PatientDelete {
    /**
     * The ID of the Facility where the patient is receiving care.
     */
    facilityId?: string;
}
