version: '3.8'

services:
  mllp-server:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "2575:2575"
    environment:
      NODE_ENV: production
      AWS_REGION: us-east-1