/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import * as Metriport from "../../../../../../api";
import * as core from "../../../../../../core";

export const Filter: core.serialization.ObjectSchema<serializers.medical.Filter.Raw, Metriport.medical.Filter> =
    core.serialization.object({
        resources: core.serialization.string(),
        dateFrom: core.serialization.string().optional(),
        dateTo: core.serialization.string().optional(),
    });

export declare namespace Filter {
    interface Raw {
        resources: string;
        dateFrom?: string | null;
        dateTo?: string | null;
    }
}
