/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import * as Metriport from "../../../../../../api";
import * as core from "../../../../../../core";

export const PatientConsolidatedDataStatus: core.serialization.Schema<
    serializers.medical.PatientConsolidatedDataStatus.Raw,
    Metriport.medical.PatientConsolidatedDataStatus
> = core.serialization.enum_(["processing", "completed", "failed"]);

export declare namespace PatientConsolidatedDataStatus {
    type Raw = "processing" | "completed" | "failed";
}
