/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Metriport from "../../..";

export interface ActivitySummary {
    durations?: Metriport.devices.ActivityDurations;
    energyExpenditure?: Metriport.devices.EnergyExpenditure;
    biometrics?: Metriport.devices.Biometrics;
}
