/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ConnectedUserInfo {
    metriportUserId: string;
    appUserId: string;
    connectedProviders?: string[];
}
