/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Metriport from "../../..";

export interface HeartRateVariability {
    rmssd?: Metriport.devices.HeartRateVariabilityMeasurement;
    sdnn?: Metriport.devices.HeartRateVariabilityMeasurement;
}
