/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Metriport from "../../..";

export interface HeartRateVariabilityMeasurement {
    avgMillis?: number;
    samplesMillis?: Metriport.devices.Sample[];
}
