/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Metriport from "../../..";

export interface HeartRate {
    minBpm?: number;
    maxBpm?: number;
    avgBpm?: number;
    restingBpm?: number;
    samplesBpm?: Metriport.devices.Sample[];
}
