/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Metriport from "../../..";

export interface NutritionFacts {
    macros?: Metriport.devices.Macros;
    micros?: Metriport.devices.Micros;
    aminos?: Metriport.devices.Aminos;
}
