/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type SourceType = "MANUAL_ENTRY" | "DEVICE";

export const SourceType = {
    Manual: "MANUAL_ENTRY",
    Device: "DEVICE",
} as const;
