/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Metriport from "../../..";

export interface TemperatureMeasurement {
    avgCelcius?: number;
    samplesCelcius?: Metriport.devices.Sample[];
}
