/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Metriport from "../../..";

export interface Temperature {
    core?: Metriport.devices.TemperatureMeasurement;
    deltaCelcius?: number;
    skin?: Metriport.devices.TemperatureMeasurement;
}
