/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "./environments";
import * as core from "./core";
import { Devices } from "./api/resources/devices/client/Client";
import { Medical } from "./api/resources/medical/client/Client";

export declare namespace MetriportClient {
    interface Options {
        environment?: core.Supplier<environments.MetriportEnvironment | string>;
        apiKey: core.Supplier<string>;
    }

    interface RequestOptions {
        timeoutInSeconds?: number;
    }
}

export class MetriportClient {
    constructor(protected readonly _options: MetriportClient.Options) {}

    protected _devices: Devices | undefined;

    public get devices(): Devices {
        return (this._devices ??= new Devices(this._options));
    }

    protected _medical: Medical | undefined;

    public get medical(): Medical {
        return (this._medical ??= new Medical(this._options));
    }
}
