/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const MetriportEnvironment = {
    Production: "https://api.metriport.com",
} as const;

export type MetriportEnvironment = typeof MetriportEnvironment.Production;
