/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface GetMetriportUserIdRequest {
    /**
     * The user ID you identify this user with in your app.
     */
    appUserId: string;
}
