# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic

from ....core.datetime_utils import serialize_datetime


class Macros(pydantic.BaseModel):
    alcohol_g: typing.Optional[int]
    carbs_g: typing.Optional[int]
    cholesterol_mg: typing.Optional[int]
    energy_kcal: typing.Optional[int]
    fat_g: typing.Optional[int]
    fiber_g: typing.Optional[int]
    protein_g: typing.Optional[int]
    sodium_mg: typing.Optional[int]
    sugar_g: typing.Optional[int]
    trans_fat_g: typing.Optional[int]
    water_ml: typing.Optional[int]

    def json(self, **kwargs: typing.Any) -> str:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().json(**kwargs_with_defaults)

    def dict(self, **kwargs: typing.Any) -> typing.Dict[str, typing.Any]:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().dict(**kwargs_with_defaults)

    class Config:
        frozen = True
        smart_union = True
        json_encoders = {dt.datetime: serialize_datetime}
