# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic

from ....core.datetime_utils import serialize_datetime


class Micros(pydantic.BaseModel):
    biotin_mg: typing.Optional[int]
    caffeine_mg: typing.Optional[int]
    calcium_mg: typing.Optional[int]
    copper_mg: typing.Optional[int]
    folate_mg: typing.Optional[int]
    folic_acid_mg: typing.Optional[int]
    iodine_mg: typing.Optional[int]
    iron_mg: typing.Optional[int]
    magnesium_mg: typing.Optional[int]
    manganese_mg: typing.Optional[int]
    phosphorus_mg: typing.Optional[int]
    potassium_mg: typing.Optional[int]
    selenium_mg: typing.Optional[int]
    vitamin_a_mg: typing.Optional[int] = pydantic.Field(alias="vitamin_A_mg")
    vitamin_b_1_mg: typing.Optional[int] = pydantic.Field(alias="vitamin_B1_mg")
    vitamin_b_2_mg: typing.Optional[int] = pydantic.Field(alias="vitamin_B2_mg")
    vitamin_b_3_mg: typing.Optional[int] = pydantic.Field(alias="vitamin_B3_mg")
    vitamin_b_5_mg: typing.Optional[int] = pydantic.Field(alias="vitamin_B5_mg")
    vitamin_b_6_mg: typing.Optional[int] = pydantic.Field(alias="vitamin_B6_mg")
    vitamin_b_12_mg: typing.Optional[int] = pydantic.Field(alias="vitamin_B12_mg")
    vitamin_c_mg: typing.Optional[int] = pydantic.Field(alias="vitamin_C_mg")
    vitamin_d_mg: typing.Optional[int] = pydantic.Field(alias="vitamin_D_mg")
    vitamin_e_mg: typing.Optional[int] = pydantic.Field(alias="vitamin_E_mg")
    vitamin_k_mg: typing.Optional[int] = pydantic.Field(alias="vitamin_K_mg")
    zinc_mg: typing.Optional[int]

    def json(self, **kwargs: typing.Any) -> str:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().json(**kwargs_with_defaults)

    def dict(self, **kwargs: typing.Any) -> typing.Dict[str, typing.Any]:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().dict(**kwargs_with_defaults)

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True
        json_encoders = {dt.datetime: serialize_datetime}
