# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

from ....core.datetime_utils import serialize_datetime
from .metriport_data import MetriportData
from .sleep_biometrics import SleepBiometrics
from .sleep_durations import SleepDurations


class Sleep(MetriportData):
    start_time: typing.Optional[str]
    end_time: typing.Optional[str]
    durations: typing.Optional[SleepDurations]
    biometrics: typing.Optional[SleepBiometrics]
    wakeup_frequency: typing.Optional[int]

    def json(self, **kwargs: typing.Any) -> str:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().json(**kwargs_with_defaults)

    def dict(self, **kwargs: typing.Any) -> typing.Dict[str, typing.Any]:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().dict(**kwargs_with_defaults)

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True
        json_encoders = {dt.datetime: serialize_datetime}
