#!/usr/bin/env node
import { IHEGateway, APIMode } from "@metriport/ihe-gateway-sdk";
import { Command } from "commander";
// import * as dotenv from "dotenv";

function metriportBanner(): string {
  return `
            ,▄,
          ▄▓███▌
      ▄▀╙   ▀▓▀    ²▄
    ▄└               ╙▌
  ,▀                   ╨▄
  ▌                     ║
                         ▌
                         ▌
,▓██▄                 ╔███▄
╙███▌                 ▀███▀
    ▀▄
      ▀╗▄         ,▄
         '╙▀▀▀▀▀╙''

        Metriport Inc.

    CQ Cert Runner
      `;
}

export const program = new Command();
program
  .name("cq-cert-runner")
  .description("Tool to run through CQ certification test cases.")
  .requiredOption(
    `--env-file <file-path>`,
    `Absolute path to the .env file containing required config. Example required file contents:
"
    `
  )
  .addHelpText("before", metriportBanner())
  .showHelpAfterError()
  .version("1.0.0");

async function main() {
  console.log(metriportBanner());
  // program.parse();
  // const options = program.opts();
  // dotenv.config({ path: options.envFile });

  const iheGateway = new IHEGateway(APIMode.dev);

  const stuff = await iheGateway.locatePatient({
    patient: {
      resourceType: "Patient",
      id: "6b20fe03-43ce-16b3-334b-13c78e9b656d",
      meta: {
        profile: ["http://hl7.org/fhir/us/core/StructureDefinition/us-core-patient"],
      },
      text: {
        status: "generated",
        div: '<div xmlns="http://www.w3.org/1999/xhtml">Generated by <a href="https://github.com/synthetichealth/synthea">Synthea</a>.Version identifier: 2512c10\n .   Person seed: 3478283699229979143  Population seed: 1685983869878</div>',
      },
      extension: [
        {
          url: "http://hl7.org/fhir/us/core/StructureDefinition/us-core-race",
          extension: [
            {
              url: "ombCategory",
              valueCoding: {
                system: "urn:oid:2.16.840.1.113883.6.238",
                code: "2106-3",
                display: "White",
              },
            },
            {
              url: "text",
              valueString: "White",
            },
          ],
        },
        {
          url: "http://hl7.org/fhir/us/core/StructureDefinition/us-core-ethnicity",
          extension: [
            {
              url: "ombCategory",
              valueCoding: {
                system: "urn:oid:2.16.840.1.113883.6.238",
                code: "2186-5",
                display: "Not Hispanic or Latino",
              },
            },
            {
              url: "text",
              valueString: "Not Hispanic or Latino",
            },
          ],
        },
        {
          url: "http://hl7.org/fhir/StructureDefinition/patient-mothersMaidenName",
          valueString: "Cordelia715 Bergstrom287",
        },
        {
          url: "http://hl7.org/fhir/us/core/StructureDefinition/us-core-birthsex",
          valueCode: "F",
        },
        {
          url: "http://hl7.org/fhir/StructureDefinition/patient-birthPlace",
          valueAddress: {
            city: "Wilmington",
            state: "Massachusetts",
            country: "US",
          },
        },
        {
          url: "http://synthetichealth.github.io/synthea/disability-adjusted-life-years",
          valueDecimal: 0.279085000570256,
        },
        {
          url: "http://synthetichealth.github.io/synthea/quality-adjusted-life-years",
          valueDecimal: 27.720914999429745,
        },
      ],
      identifier: [
        {
          system: "https://github.com/synthetichealth/synthea",
          value: "6b20fe03-43ce-16b3-334b-13c78e9b656d",
        },
        {
          type: {
            coding: [
              {
                system: "http://terminology.hl7.org/CodeSystem/v2-0203",
                code: "MR",
                display: "Medical Record Number",
              },
            ],
            text: "Medical Record Number",
          },
          system: "http://hospital.smarthealthit.org",
          value: "6b20fe03-43ce-16b3-334b-13c78e9b656d",
        },
        {
          type: {
            coding: [
              {
                system: "http://terminology.hl7.org/CodeSystem/v2-0203",
                code: "SS",
                display: "Social Security Number",
              },
            ],
            text: "Social Security Number",
          },
          system: "http://hl7.org/fhir/sid/us-ssn",
          value: "999-69-3057",
        },
        {
          type: {
            coding: [
              {
                system: "http://terminology.hl7.org/CodeSystem/v2-0203",
                code: "DL",
                display: "Driver's license number",
              },
            ],
            text: "Driver's license number",
          },
          system: "urn:oid:2.16.840.1.113883.4.3.25",
          value: "S99977383",
        },
        {
          type: {
            coding: [
              {
                system: "http://terminology.hl7.org/CodeSystem/v2-0203",
                code: "PPN",
                display: "Passport Number",
              },
            ],
            text: "Passport Number",
          },
          system: "http://standardhealthrecord.org/fhir/StructureDefinition/passportNumber",
          value: "X52789491X",
        },
      ],
      name: [
        {
          use: "official",
          family: "O'Kon634",
          given: ["Tayna279", "Ayesha583"],
          prefix: ["Mrs."],
        },
        {
          use: "maiden",
          family: "Upton904",
          given: ["Tayna279", "Ayesha583"],
          prefix: ["Mrs."],
        },
      ],
      telecom: [
        {
          system: "phone",
          value: "555-970-5730",
          use: "home",
        },
      ],
      gender: "female",
      birthDate: "1994-07-21",
      address: [
        {
          extension: [
            {
              url: "http://hl7.org/fhir/StructureDefinition/geolocation",
              extension: [
                {
                  url: "latitude",
                  valueDecimal: 42.64966004439386,
                },
                {
                  url: "longitude",
                  valueDecimal: -72.29542688089437,
                },
              ],
            },
          ],
          line: ["656 Breitenberg Vale Unit 19"],
          city: "Orange",
          state: "MA",
          postalCode: "01364",
          country: "US",
        },
      ],
      maritalStatus: {
        coding: [
          {
            system: "http://terminology.hl7.org/CodeSystem/v3-MaritalStatus",
            code: "M",
            display: "Married",
          },
        ],
        text: "Married",
      },
      multipleBirthBoolean: false,
      communication: [
        {
          language: {
            coding: [
              {
                system: "urn:ietf:bcp:47",
                code: "en-US",
                display: "English (United States)",
              },
            ],
            text: "English (United States)",
          },
        },
      ],
    },
    cxId: "",
    xcpdGateways: [],
    principalCareProviderNPIs: [],
    requestId: "",
  });

  console.log(stuff);
}

main();
