/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     "2.16.840.1.113883.3.666.5.2004.4.2005"
 *
 * @example
 *     "2.16.840.1.113883.3.666.123"
 */
export type FacilityId = string;
