/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Metriport from "../../../../..";

/**
 * @example
 *     {
 *         type: "driversLicense",
 *         state: Metriport.UsState.Ca,
 *         value: "51227265"
 *     }
 */
export type PersonalIdentifier = Metriport.medical.PersonalIdentifier.DriversLicense;

export declare namespace PersonalIdentifier {
    interface DriversLicense extends Metriport.medical.DriversLicense {
        type: "driversLicense";
    }
}
