default:
  outputs:
    development:
      account: "{{ env_var('DBT_SNOWFLAKE_CI_ACCOUNT') }}"
      role: "{{ env_var('DBT_SNOWFLAKE_CI_ROLE') }}"
      user: "{{ env_var('DBT_SNOWFLAKE_CI_USER') }}"
      password: "{{ env_var('DBT_SNOWFLAKE_CI_PASSWORD') }}"
      warehouse: "{{ env_var('DBT_SNOWFLAKE_CI_WAREHOUSE') }}"
      database: "DEVELOPMENT_METRICS_{{ env_var('CX_ID') }}"
      schema: public
      threads: 5
      type: snowflake
    staging:
      account: "{{ env_var('DBT_SNOWFLAKE_CI_ACCOUNT') }}"
      role: "{{ env_var('DBT_SNOWFLAKE_CI_ROLE') }}"
      user: "{{ env_var('DBT_SNOWFLAKE_CI_USER') }}"
      password: "{{ env_var('DBT_SNOWFLAKE_CI_PASSWORD') }}"
      warehouse: "{{ env_var('DBT_SNOWFLAKE_CI_WAREHOUSE') }}"
      database: "STAGING_METRICS_{{ env_var('CX_ID') }}"
      schema: public
      threads: 5
      type: snowflake
    production:
      account: "{{ env_var('DBT_SNOWFLAKE_CI_ACCOUNT') }}"
      role: "{{ env_var('DBT_SNOWFLAKE_CI_ROLE') }}"
      user: "{{ env_var('DBT_SNOWFLAKE_CI_USER') }}"
      password: "{{ env_var('DBT_SNOWFLAKE_CI_PASSWORD') }}"
      warehouse: "{{ env_var('DBT_SNOWFLAKE_CI_WAREHOUSE') }}"
      database: "PRODUCTION_METRICS_{{ env_var('CX_ID') }}"
      schema: public
      threads: 5
      type: snowflake

  target: development
