title: fhirUserConfiguration
type: object
description: User specific configuration for the Medplum application.
properties:
  resourceType:
    type: string
    enum:
      - UserConfiguration
  id:
    $ref: ./fhirid.yml
    nullable: true
    description: >-
      The logical id of the resource, as used in the URL for the resource. Once
      assigned, this value never changes.
  meta:
    $ref: ./fhirMeta.yml
    nullable: true
    description: >-
      The metadata about the resource. This is content that is maintained by the
      infrastructure. Changes to the content might not always be associated with
      version changes to the resource.
  implicitRules:
    $ref: ./fhiruri.yml
    nullable: true
    description: >-
      A reference to a set of rules that were followed when the resource was
      constructed, and which must be understood when processing the content.
      Often, this is a reference to an implementation guide that defines the
      special rules along with other profiles etc.
  language:
    $ref: ./fhircode.yml
    nullable: true
    description: The base language in which the resource is written.
  name:
    type: string
    nullable: true
    description: A name associated with the UserConfiguration.
  menu:
    type: array
    items:
      $ref: ./fhirUserConfigurationMenu.yml
    nullable: true
    description: Optional menu of shortcuts to URLs.
  search:
    type: array
    items:
      $ref: ./fhirUserConfigurationSearch.yml
    nullable: true
    description: Shortcut links to URLs.
  option:
    type: array
    items:
      $ref: ./fhirUserConfigurationOption.yml
    nullable: true
    description: User options that control the display of the application.
required:
  - resourceType
