title: fhirUserConfigurationSearch
type: object
description: Shortcut links to URLs.
properties:
  name:
    type: string
    description: The human friendly name of the link.
  criteria:
    type: string
    description: >-
      The rules that the server should use to determine which resources to
      return.
required:
  - name
  - criteria
