title: fhirDomainConfiguration
type: object
description: Domain specific configuration for the Medplum application.
properties:
  resourceType:
    type: string
    enum:
      - DomainConfiguration
  id:
    $ref: ./fhirid.yml
    nullable: true
    description: >-
      The logical id of the resource, as used in the URL for the resource. Once
      assigned, this value never changes.
  meta:
    $ref: ./fhirMeta.yml
    nullable: true
    description: >-
      The metadata about the resource. This is content that is maintained by the
      infrastructure. Changes to the content might not always be associated with
      version changes to the resource.
  implicitRules:
    $ref: ./fhiruri.yml
    nullable: true
    description: >-
      A reference to a set of rules that were followed when the resource was
      constructed, and which must be understood when processing the content.
      Often, this is a reference to an implementation guide that defines the
      special rules along with other profiles etc.
  language:
    $ref: ./fhircode.yml
    nullable: true
    description: The base language in which the resource is written.
  domain:
    $ref: ./fhiruri.yml
    description: Globally unique domain name for this configuration.
  identityProvider:
    $ref: ./fhirIdentityProvider.yml
    nullable: true
    description: Optional external Identity Provider (IdP) for the domain name.
required:
  - resourceType
  - domain
