/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import * as Metriport from "../../../../../../api";
import * as core from "../../../../../../core";

export const Coding: core.serialization.ObjectSchema<serializers.medical.Coding.Raw, Metriport.medical.Coding> =
    core.serialization.object({
        system: core.serialization.string().optional(),
        code: core.serialization.string().optional(),
        display: core.serialization.string().optional(),
    });

export declare namespace Coding {
    interface Raw {
        system?: string | null;
        code?: string | null;
        display?: string | null;
    }
}
