/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import * as Metriport from "../../../../../../api";
import * as core from "../../../../../../core";

export const ConversionType: core.serialization.Schema<
    serializers.medical.ConversionType.Raw,
    Metriport.medical.ConversionType
> = core.serialization.enum_(["html", "pdf"]);

export declare namespace ConversionType {
    type Raw = "html" | "pdf";
}
