/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import * as Metriport from "../../../../../../api";
import * as core from "../../../../../../core";

export const ListDocumentsResponse: core.serialization.ObjectSchema<
    serializers.medical.ListDocumentsResponse.Raw,
    Metriport.medical.ListDocumentsResponse
> = core.serialization.object({
    documents: core.serialization.list(
        core.serialization.lazyObject(async () => (await import("../../../../..")).medical.DocumentReference)
    ),
});

export declare namespace ListDocumentsResponse {
    interface Raw {
        documents: serializers.medical.DocumentReference.Raw[];
    }
}
