/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Metriport from "../../../../..";

export interface BaseFacility {
    /** The name of your Facility. This is the actual address where a patient will receive care (can be virtual) - for example `Care Facility, LLC`. */
    name: string;
    /** The 10 digit National Provider Identifier (NPI) that will be used to make requests on behalf of the Facility. */
    npi: string;
    /** The Taxpayer Identification Number (TIN) of the Facility. */
    tin?: string;
    /** Whether or not this Facility is currently active - this is usually `true`. */
    active?: boolean;
    address: Metriport.Address;
}
