# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import typing_extensions

from .drivers_license import DriversLicense


class PersonalIdentifier_DriversLicense(DriversLicense):
    type: typing_extensions.Literal["driversLicense"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


PersonalIdentifier = typing.Union[PersonalIdentifier_DriversLicense]
