# This file was auto-generated by Fern from our API Definition.

import typing

from .resources_searchable_by_patient import ResourcesSearchableByPatient
from .resources_searchable_by_subject import ResourcesSearchableBySubject

ResourceTypeForConsolidation = typing.Union[ResourcesSearchableByPatient, ResourcesSearchableBySubject]
