/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         system: "http://snomed.info/sct",
 *         code: "62479008",
 *         display: "Diagnoses"
 *     }
 */
export interface Coding {
    /** Identity of the terminology system. */
    system?: string;
    /** Symbol in syntax defined by the system. */
    code?: string;
    /** Representation defined by the system. */
    display?: string;
}
