/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Metriport from "../../../../..";

/**
 * @example
 *     {
 *         download: {
 *             status: Metriport.medical.DocumentQueryStatus.Completed,
 *             total: 100,
 *             successful: 98,
 *             errors: 2
 *         },
 *         convert: {
 *             status: Metriport.medical.DocumentQueryStatus.Processing
 *         }
 *     }
 */
export interface DocumentQuery {
    download?: Metriport.medical.Progress;
    convert?: Metriport.medical.Progress;
}
