/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * A json object containing the URL will be returned.
 *
 * @example
 *     {
 *         url: "abc123-def456"
 *     }
 */
export interface DocumentUrl {
    /** The presigned URL. */
    url?: string;
}
