/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type DocumentQueryStatus = "processing" | "completed" | "failed";

export const DocumentQueryStatus = {
    Processing: "processing",
    Completed: "completed",
    Failed: "failed",
} as const;
