/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../../../../../errors";
import express from "express";

export class InvalidFhirError extends errors.MetriportApiError {
    constructor() {
        super("InvalidFhirError");
        Object.setPrototypeOf(this, InvalidFhirError.prototype);
    }

    public async send(res: express.Response): Promise<void> {
        res.sendStatus(400);
    }
}
