/**
 * This file was auto-generated by Fern from our API Definition.
 */

import core.ClientOptions;
import core.Environment;
import java.lang.String;

public final class MetriportBuilder {
  private ClientOptions.Builder clientOptionsBuilder = ClientOptions.builder();

  private Environment environment = Environment.PRODUCTION;

  public MetriportBuilder apiKey(String apiKey) {
    this.clientOptionsBuilder.addHeader("X-API-Key", apiKey);
    return this;
  }

  public MetriportBuilder environment(Environment environment) {
    this.environment = environment;
    return this;
  }

  public MetriportBuilder url(String url) {
    this.environment = Environment.custom(url);
    return this;
  }

  public Metriport build() {
    clientOptionsBuilder.environment(this.environment);
    return new Metriport(clientOptionsBuilder.build());
  }
}
