
-- SELECT statement for MedicationRequest
SELECT 
    resourcetype,
    id,
    meta_versionid,
    meta_lastupdated,
    meta_source,
    identifier_0_system,
    identifier_0_value,
    identifier_1_system,
    identifier_1_value,
    identifier_2_system,
    identifier_2_value,
    status,
    intent,
    medicationreference_reference,
    subject_reference,
    authoredon,
    requester_reference,
    identifier_0_type_text,
    identifier_1_type_text,
    identifier_2_type_text,
    identifier_3_system,
    identifier_3_value,
    identifier_3_type_text,
    identifier_0_assigner_display,
    identifier_1_assigner_display,
    identifier_2_assigner_display,
    identifier_3_assigner_display,
    identifier_4_system,
    identifier_4_value,
    identifier_4_assigner_display,
    identifier_5_system,
    identifier_5_value,
    identifier_6_system,
    identifier_6_value,
    identifier_7_system,
    identifier_7_value,
    identifier_8_system,
    identifier_8_value,
    identifier_9_system,
    identifier_9_value,
    filename,
    processed_date 
FROM {{source('raw', 'medicationrequest') }} x

QUALIFY rank() over(partition by filename order by processed_date desc) = 1