/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The type of contributor.
 */
export type ContributorType = "author" | "editor" | "reviewer" | "endorser";

export const ContributorType = {
    Author: "author",
    Editor: "editor",
    Reviewer: "reviewer",
    Endorser: "endorser",
} as const;
