/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Identifies the purpose for the contact point.
 */
export type ContactPointUse = "home" | "work" | "temp" | "old" | "mobile";

export const ContactPointUse = {
    Home: "home",
    Work: "work",
    Temp: "temp",
    Old: "old",
    Mobile: "mobile",
} as const;
