/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as MetriportApi from "../../..";

/**
 * Describes a required data item for evaluation in terms of the type of data, and optional code or date-based filters of the data.
 */
export interface DataRequirement {
    /** Unique id for the element within a resource (for internal references). This may be any string value that does not contain spaces. */
    id?: string;
    /** May be used to represent additional information that is not part of the basic definition of the element. To make the use of extensions safe and manageable, there is a strict set of governance applied to the definition and use of extensions. Though any implementer can define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension. */
    extension?: MetriportApi.fhir.Extension[];
    /** The type of the required data, specified as the type name of a resource. For profiles, this value is set to the type of the base resource of the profile. */
    type?: MetriportApi.fhir.Code;
    /** The profile of the required data, specified as the uri of the profile definition. */
    profile?: MetriportApi.fhir.Canonical[];
    /** The intended subjects of the data requirement. If this element is not provided, a Patient subject is assumed. */
    subjectCodeableConcept?: MetriportApi.fhir.CodeableConcept;
    /** The intended subjects of the data requirement. If this element is not provided, a Patient subject is assumed. */
    subjectReference?: MetriportApi.fhir.Reference;
    /** Indicates that specific elements of the type are referenced by the knowledge module and must be supported by the consumer in order to obtain an effective evaluation. This does not mean that a value is required for this element, only that the consuming system must understand the element and be able to provide values for it if they are available. The value of mustSupport SHALL be a FHIRPath resolveable on the type of the DataRequirement. The path SHALL consist only of identifiers, constant indexers, and .resolve() (see the [Simple FHIRPath Profile](fhirpath.html#simple) for full details). */
    mustSupport?: string[];
    /** Code filters specify additional constraints on the data, specifying the value set of interest for a particular element of the data. Each code filter defines an additional constraint on the data, i.e. code filters are AND'ed, not OR'ed. */
    codeFilter?: MetriportApi.fhir.DataRequirementCodeFilter[];
    /** Date filters specify additional constraints on the data in terms of the applicable date range for specific elements. Each date filter specifies an additional constraint on the data, i.e. date filters are AND'ed, not OR'ed. */
    dateFilter?: MetriportApi.fhir.DataRequirementDateFilter[];
    /** Specifies a maximum number of results that are required (uses the \_count search parameter). */
    limit?: MetriportApi.fhir.PositiveInt;
    /** Specifies the order of the results to be returned. */
    sort?: MetriportApi.fhir.DataRequirementSort[];
}
