/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * How the value should be understood and represented - whether the actual value is greater or less than the stated value due to measurement issues; e.g. if the comparator is "<" , then the real value is < stated value.
 */
export type DurationComparator = "<" | "<=" | ">=" | ">";

export const DurationComparator = {
    LessThan: "<",
    LessThanOrEqualTo: "<=",
    GreaterThanOrEqualTo: ">=",
    GreaterThan: ">",
} as const;
