/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The media type of the language for the expression.
 */
export type ExpressionLanguage = "text/cql" | "text/fhirpath" | "application/x-fhir-query";

export const ExpressionLanguage = {
    TextCql: "text/cql",
    TextFhirpath: "text/fhirpath",
    ApplicationXFhirQuery: "application/x-fhir-query",
} as const;
