/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as MetriportApi from "../../..";

/**
 * The metadata about a resource. This is content in the resource that is maintained by the infrastructure. Changes to the content might not always be associated with version changes to the resource.
 */
export interface Meta {
    /** Unique id for the element within a resource (for internal references). This may be any string value that does not contain spaces. */
    id?: string;
    /** May be used to represent additional information that is not part of the basic definition of the element. To make the use of extensions safe and manageable, there is a strict set of governance applied to the definition and use of extensions. Though any implementer can define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension. */
    extension?: MetriportApi.fhir.Extension[];
    /** The version specific identifier, as it appears in the version portion of the URL. This value changes when the resource is created, updated, or deleted. */
    versionId?: MetriportApi.fhir.Id;
    /** When the resource last changed - e.g. when the version changed. */
    lastUpdated?: MetriportApi.fhir.Instant;
    /** A uri that identifies the source system of the resource. This provides a minimal amount of [[[Provenance]]] information that can be used to track or differentiate the source of information in the resource. The source may identify another FHIR server, document, message, database, etc. */
    source?: MetriportApi.fhir.Uri;
    /** A list of profiles (references to [[[StructureDefinition]]] resources) that this resource claims to conform to. The URL is a reference to [[[StructureDefinition.url]]]. */
    profile?: MetriportApi.fhir.Canonical[];
    /** Security labels applied to this resource. These tags connect specific resources to the overall security policy and infrastructure. */
    security?: MetriportApi.fhir.Coding[];
    /** Tags applied to this resource. Tags are intended to be used to identify and relate resources to process and workflow, and applications are not required to consider the tags when interpreting the meaning of a resource. */
    tag?: MetriportApi.fhir.Coding[];
    /** The project that contains this resource. */
    project?: MetriportApi.fhir.Uri;
    /** The individual, device or organization who initiated the last change. */
    author?: MetriportApi.fhir.Reference;
    /** Optional account reference that can be used for sub-project compartments. */
    account?: MetriportApi.fhir.Reference;
    /** The list of compartments containing this resource. This is readonly and is set by the server. */
    compartment?: MetriportApi.fhir.Reference[];
}
