/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.medical.patient.types;

import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.JsonParseException;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import core.ObjectMappers;
import java.io.IOException;
import java.lang.IllegalArgumentException;
import java.lang.IllegalStateException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import resources.commons.types.Address;

@JsonDeserialize(
    using = Addresses.Deserializer.class
)
public final class Addresses {
  private final Object value;

  private final int type;

  private Addresses(Object value, int type) {
    this.value = value;
    this.type = type;
  }

  @JsonValue
  public Object get() {
    return this.value;
  }

  public <T> T visit(Visitor<T> visitor) {
    if(this.type == 0) {
      return visitor.visit((Address) this.value);
    } else if(this.type == 1) {
      return visitor.visit((List<Address>) this.value);
    }
    throw new IllegalStateException("Failed to visit value. This should never happen.");
  }

  @Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof Addresses && equalTo((Addresses) other);
  }

  private boolean equalTo(Addresses other) {
    return value.equals(other.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(this.value);
  }

  @Override
  public String toString() {
    return this.value.toString();
  }

  public static Addresses of(Address value) {
    return new Addresses(value, 0);
  }

  public static Addresses of(List<Address> value) {
    return new Addresses(value, 1);
  }

  public interface Visitor<T> {
    T visit(Address value);

    T visit(List<Address> value);
  }

  static final class Deserializer extends StdDeserializer<Addresses> {
    Deserializer() {
      super(Addresses.class);
    }

    @Override
    public Addresses deserialize(JsonParser p, DeserializationContext ctxt) throws IOException {
      Object value = p.readValueAs(Object.class);
      try {
        return of(ObjectMappers.JSON_MAPPER.convertValue(value, Address.class));
      } catch(IllegalArgumentException e) {
      }
      try {
        return of(ObjectMappers.JSON_MAPPER.convertValue(value, new TypeReference<List<Address>>() {}));
      } catch(IllegalArgumentException e) {
      }
      throw new JsonParseException(p, "Failed to deserialize");
    }
  }
}
