/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.medical.patient.types;

import java.lang.String;
import java.util.List;
import java.util.Optional;

public interface IBasePatient {
  String getFirstName();

  String getLastName();

  String getDob();

  String getGenderAtBirth();

  Optional<List<PersonalIdentifier>> getPersonalIdentifiers();

  Optional<Addresses> getAddress();

  Optional<Contacts> getContact();
}
