/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as MetriportApi from "../../../../api";
import * as core from "../../../../core";

export const AddressType: core.serialization.Schema<serializers.fhir.AddressType.Raw, MetriportApi.fhir.AddressType> =
    core.serialization.enum_(["postal", "physical", "both"]);

export declare namespace AddressType {
    type Raw = "postal" | "physical" | "both";
}
