/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as MetriportApi from "../../../../api";
import * as core from "../../../../core";

export const Base64Binary: core.serialization.Schema<
    serializers.fhir.Base64Binary.Raw,
    MetriportApi.fhir.Base64Binary
> = core.serialization.string();

export declare namespace Base64Binary {
    type Raw = string;
}
