/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as MetriportApi from "../../../../api";
import * as core from "../../../../core";

export const BundleRequestMethod: core.serialization.Schema<
    serializers.fhir.BundleRequestMethod.Raw,
    MetriportApi.fhir.BundleRequestMethod
> = core.serialization.enum_(["GET", "HEAD", "POST", "PUT", "DELETE", "PATCH"]);

export declare namespace BundleRequestMethod {
    type Raw = "GET" | "HEAD" | "POST" | "PUT" | "DELETE" | "PATCH";
}
