/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as MetriportApi from "../../../../api";
import * as core from "../../../../core";

export const BundleType: core.serialization.Schema<serializers.fhir.BundleType.Raw, MetriportApi.fhir.BundleType> =
    core.serialization.enum_([
        "document",
        "message",
        "transaction",
        "transaction-response",
        "batch",
        "batch-response",
        "history",
        "searchset",
        "collection",
    ]);

export declare namespace BundleType {
    type Raw =
        | "document"
        | "message"
        | "transaction"
        | "transaction-response"
        | "batch"
        | "batch-response"
        | "history"
        | "searchset"
        | "collection";
}
