/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as MetriportApi from "../../../../api";
import * as core from "../../../../core";

export const CountComparator: core.serialization.Schema<
    serializers.fhir.CountComparator.Raw,
    MetriportApi.fhir.CountComparator
> = core.serialization.enum_(["<", "<=", ">=", ">"]);

export declare namespace CountComparator {
    type Raw = "<" | "<=" | ">=" | ">";
}
