/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as MetriportApi from "../../../../api";
import * as core from "../../../../core";

export const DataRequirementSortDirection: core.serialization.Schema<
    serializers.fhir.DataRequirementSortDirection.Raw,
    MetriportApi.fhir.DataRequirementSortDirection
> = core.serialization.enum_(["ascending", "descending"]);

export declare namespace DataRequirementSortDirection {
    type Raw = "ascending" | "descending";
}
