/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as MetriportApi from "../../../../api";
import * as core from "../../../../core";

export const DurationComparator: core.serialization.Schema<
    serializers.fhir.DurationComparator.Raw,
    MetriportApi.fhir.DurationComparator
> = core.serialization.enum_(["<", "<=", ">=", ">"]);

export declare namespace DurationComparator {
    type Raw = "<" | "<=" | ">=" | ">";
}
