/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as MetriportApi from "../../../../api";
import * as core from "../../../../core";

export const Id: core.serialization.Schema<serializers.fhir.Id.Raw, MetriportApi.fhir.Id> = core.serialization.string();

export declare namespace Id {
    type Raw = string;
}
