/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as MetriportApi from "../../../../api";
import * as core from "../../../../core";

export const PositiveInt: core.serialization.Schema<serializers.fhir.PositiveInt.Raw, MetriportApi.fhir.PositiveInt> =
    core.serialization.number();

export declare namespace PositiveInt {
    type Raw = number;
}
