/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as MetriportApi from "../../../../api";
import * as core from "../../../../core";

export const TimingRepeatPeriodUnit: core.serialization.Schema<
    serializers.fhir.TimingRepeatPeriodUnit.Raw,
    MetriportApi.fhir.TimingRepeatPeriodUnit
> = core.serialization.enum_(["s", "min", "h", "d", "wk", "mo", "a"]);

export declare namespace TimingRepeatPeriodUnit {
    type Raw = "s" | "min" | "h" | "d" | "wk" | "mo" | "a";
}
