/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as MetriportApi from "../../../../api";
import * as core from "../../../../core";

export const Uri: core.serialization.Schema<serializers.fhir.Uri.Raw, MetriportApi.fhir.Uri> =
    core.serialization.string();

export declare namespace Uri {
    type Raw = string;
}
