[GenConfig]
outputpath = Patient.csv
inputformat = json
writemode = append
anchor = name

[Struct]
anchor_index = GetIndex:
extension_0_url = Anchor:extension.0.url
extension_0_valuecoding_code = Anchor:extension.0.valueCoding.code
extension_0_valuecoding_display = Anchor:extension.0.valueCoding.display
extension_0_valuecoding_system = Anchor:extension.0.valueCoding.system
extension_0_valuestring = Anchor:extension.0.valueString
extension_0_valueuri = Anchor:extension.0.valueUri
extension_1_url = Anchor:extension.1.url
extension_1_valuecoding_code = Anchor:extension.1.valueCoding.code
extension_1_valuecoding_display = Anchor:extension.1.valueCoding.display
extension_1_valuecoding_system = Anchor:extension.1.valueCoding.system
extension_1_valuestring = Anchor:extension.1.valueString
extension_1_valueuri = Anchor:extension.1.valueUri
extension_2_url = Anchor:extension.2.url
extension_2_valuecoding_code = Anchor:extension.2.valueCoding.code
extension_2_valuecoding_display = Anchor:extension.2.valueCoding.display
extension_2_valuecoding_system = Anchor:extension.2.valueCoding.system
extension_2_valuestring = Anchor:extension.2.valueString
extension_2_valueuri = Anchor:extension.2.valueUri
extension_3_url = Anchor:extension.3.url
extension_3_valuecoding_code = Anchor:extension.3.valueCoding.code
extension_3_valuecoding_display = Anchor:extension.3.valueCoding.display
extension_3_valuecoding_system = Anchor:extension.3.valueCoding.system
extension_3_valuestring = Anchor:extension.3.valueString
extension_3_valueuri = Anchor:extension.3.valueUri
extension_4_url = Anchor:extension.4.url
extension_4_valuecoding_code = Anchor:extension.4.valueCoding.code
extension_4_valuecoding_display = Anchor:extension.4.valueCoding.display
extension_4_valuecoding_system = Anchor:extension.4.valueCoding.system
extension_4_valuestring = Anchor:extension.4.valueString
extension_4_valueuri = Anchor:extension.4.valueUri
family = Anchor:family
given_0 = Anchor:given.0
given_1 = Anchor:given.1
given_2 = Anchor:given.2
given_3 = Anchor:given.3
given_4 = Anchor:given.4
given_5 = Anchor:given.5
given_6 = Anchor:given.6
given_7 = Anchor:given.7
given_8 = Anchor:given.8
given_9 = Anchor:given.9
patient_id = id
period_end = Anchor:period.end
period_start = Anchor:period.start
prefix_0 = Anchor:prefix.0
prefix_1 = Anchor:prefix.1
prefix_2 = Anchor:prefix.2
prefix_3 = Anchor:prefix.3
prefix_4 = Anchor:prefix.4
suffix_0 = Anchor:suffix.0
suffix_1 = Anchor:suffix.1
suffix_2 = Anchor:suffix.2
suffix_3 = Anchor:suffix.3
suffix_4 = Anchor:suffix.4
text = Anchor:text
use = Anchor:use
# end of alphabetical sorting
filename = Filename:
processed_date = GetDate:

[anchor_paths]
extension.0.url = extension.0.url
extension.0.valueString = extension.0.valueString
extension.0.valueUri = extension.0.valueUri
extension.0.valueCoding.code = extension.0.valueCoding.code
extension.0.valueCoding.display = extension.0.valueCoding.display
extension.0.valueCoding.system = extension.0.valueCoding.system
extension.1.url = extension.1.url
extension.1.valueString = extension.1.valueString
extension.1.valueUri = extension.1.valueUri
extension.1.valueCoding.code = extension.1.valueCoding.code
extension.1.valueCoding.display = extension.1.valueCoding.display
extension.1.valueCoding.system = extension.1.valueCoding.system
extension.2.url = extension.2.url
extension.2.valueString = extension.2.valueString
extension.2.valueUri = extension.2.valueUri
extension.2.valueCoding.code = extension.2.valueCoding.code
extension.2.valueCoding.display = extension.2.valueCoding.display
extension.2.valueCoding.system = extension.2.valueCoding.system
extension.3.url = extension.3.url
extension.3.valueString = extension.3.valueString
extension.3.valueUri = extension.3.valueUri
extension.3.valueCoding.code = extension.3.valueCoding.code
extension.3.valueCoding.display = extension.3.valueCoding.display
extension.3.valueCoding.system = extension.3.valueCoding.system
extension.4.url = extension.4.url
extension.4.valueString = extension.4.valueString
extension.4.valueUri = extension.4.valueUri
extension.4.valueCoding.code = extension.4.valueCoding.code
extension.4.valueCoding.display = extension.4.valueCoding.display
extension.4.valueCoding.system = extension.4.valueCoding.system
family = family
given.0 = given.0
given.1 = given.1
given.2 = given.2
given.3 = given.3
given.4 = given.4
given.5 = given.5
given.6 = given.6
given.7 = given.7
given.8 = given.8
given.9 = given.9
period.end = period.end
period.start = period.start
prefix.0 = prefix.0
prefix.1 = prefix.1
prefix.2 = prefix.2
prefix.3 = prefix.3
prefix.4 = prefix.4
suffix.0 = suffix.0
suffix.1 = suffix.1
suffix.2 = suffix.2
suffix.3 = suffix.3
suffix.4 = suffix.4
text = text
use = use

[root_paths]

