select
    t.id,
    t.meta_source,
    t.identifier_0_system,
    t.identifier_0_value,
    t.identifier_1_system,
    t.identifier_1_value,
    t.identifier_2_system,
    t.identifier_2_value,
    t.identifier_3_system,
    t.identifier_3_value,
    t.identifier_4_system,
    t.identifier_4_value,
    t.extension_0_url,
    t.extension_0_valuestring,
    t.extension_0_valuecoding_code,
    t.extension_0_valuecoding_display,
    t.extension_0_valuecoding_system,
    t.extension_1_url,
    t.extension_1_valuestring,
    t.extension_1_valuecoding_code,
    t.extension_1_valuecoding_display,
    t.extension_1_valuecoding_system,
    t.extension_2_url,
    t.extension_2_valuestring,
    t.extension_2_valuecoding_code,
    t.extension_2_valuecoding_display,
    t.extension_2_valuecoding_system,
    t.birthdate,
    t.gender,
    t.name_0_family,
    t.name_0_given_0,
    t.m_patient_id,
    t.m_job_id,
    t.m_created_at,
    t.m_updated_at,
    t.m_deleted_at,
    '{{ var('input_job_id') }}' as raw_to_core_job_id
from {{ source('raw', 'patient_active' if target.name == 'postgres' else 'patient') }} as t
inner join {{ source('raw', 'latest_metriport_incremental_job') }} j on t.m_patient_id = j.m_patient_id and t.m_job_id = j.id and j.m_created_at > '{{ var("lookback_timestamp") }}'::timestamp

