select
    t.id,
    t.meta_source,
    t.extension_0_url,
    t.extension_0_valuestring,
    t.extension_0_valuecoding_code,
    t.extension_0_valuecoding_display,
    t.extension_0_valuecoding_system,
    t.extension_1_url,
    t.extension_1_valuestring,
    t.extension_1_valuecoding_code,
    t.extension_1_valuecoding_display,
    t.extension_1_valuecoding_system,
    t.extension_2_url,
    t.extension_2_valuestring,
    t.extension_2_valuecoding_code,
    t.extension_2_valuecoding_display,
    t.extension_2_valuecoding_system,
    t.address_0_city,
    t.address_0_country,
    t.address_0_line_0,
    t.address_0_line_1,
    t.address_0_postalcode,
    t.address_0_state,
    t.address_0_text,
    t.managingorganization_reference,
    t.name,
    t.physicaltype_coding_0_display,
    t.type_coding_0_display,
    t.m_patient_id,
    t.m_job_id,
    t.m_created_at,
    t.m_updated_at,
    t.m_deleted_at,
    '{{ var('input_job_id') }}' as raw_to_core_job_id
from {{ source('raw', 'location_active' if target.name == 'postgres' else 'location') }} as t
inner join {{ source('raw', 'latest_metriport_incremental_job') }} j on t.m_patient_id = j.m_patient_id and t.m_job_id = j.id and j.m_created_at > '{{ var("lookback_timestamp") }}'::timestamp

