select
    t.id,
    t.meta_source,
    t.extension_0_url,
    t.extension_0_valuestring,
    t.extension_0_valuecoding_code,
    t.extension_0_valuecoding_display,
    t.extension_0_valuecoding_system,
    t.extension_1_url,
    t.extension_1_valuestring,
    t.extension_1_valuecoding_code,
    t.extension_1_valuecoding_display,
    t.extension_1_valuecoding_system,
    t.extension_2_url,
    t.extension_2_valuestring,
    t.extension_2_valuecoding_code,
    t.extension_2_valuecoding_display,
    t.extension_2_valuecoding_system,
    t.subject_reference,
    t.authoredon,
    t.dosageinstruction_0_doseandrate_0_dosequantity_unit,
    t.dosageinstruction_0_doseandrate_0_dosequantity_value,
    t.encounter_reference,
    t.intent,
    t.medicationreference_reference,
    t.note_0_text,
    t.reasonreference_0_reference,
    t.reasonreference_1_reference,
    t.reasonreference_2_reference,
    t.reasonreference_3_reference,
    t.reasonreference_4_reference,
    t.reasonreference_5_reference,
    t.reasonreference_6_reference,
    t.reasonreference_7_reference,
    t.reasonreference_8_reference,
    t.reasonreference_9_reference,
    t.requester_reference,
    t.status,
    t.m_patient_id,
    t.m_job_id,
    t.m_created_at,
    t.m_updated_at,
    t.m_deleted_at,
    '{{ var('input_job_id') }}' as raw_to_core_job_id
from {{ source('raw', 'medicationrequest_active' if target.name == 'postgres' else 'medicationrequest') }} as t
inner join {{ source('raw', 'latest_metriport_incremental_job') }} j on t.m_patient_id = j.m_patient_id and t.m_job_id = j.id and j.m_created_at > '{{ var("lookback_timestamp") }}'::timestamp

