/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.medical.document.types;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Override;
import java.lang.String;

public enum DocumentQueryStatus {
  PROCESSING("processing"),

  COMPLETED("completed"),

  FAILED("failed");

  private final String value;

  DocumentQueryStatus(String value) {
    this.value = value;
  }

  @JsonValue
  @Override
  public String toString() {
    return this.value;
  }
}
