/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Metriport from "../../../../../..";

export interface OrganizationUpdateRequest {
    eTag?: string;
    /**
     * The name of your organization.
     * This is usually your legal corporate entity name -
     * for example `Metriport Inc.`.
     *
     */
    name: string;
    /** The type of your organization. */
    type: Metriport.medical.OrgType;
    location: Metriport.Address;
}
