import { BadRequestError } from "../../error/bad-request";

export function normalizeStateSafe(state: string): USState | undefined {
  const trimmedState = state.trim();
  const keyFromEntries = Object.entries(states).find(
    ([key, value]) =>
      key.toLowerCase() === trimmedState.toLowerCase() ||
      value.toLowerCase() === trimmedState.toLowerCase()
  );
  return keyFromEntries?.[0] as USState | undefined;
}

export function normalizeState(state: string): USState {
  const stateOrUndefined = normalizeStateSafe(state);
  if (!stateOrUndefined) throw new BadRequestError("Invalid state", undefined, { state });
  return stateOrUndefined;
}

export enum USState {
  AL = "AL",
  AK = "AK",
  AZ = "AZ",
  AR = "AR",
  CA = "CA",
  CO = "CO",
  CT = "CT",
  DE = "DE",
  DC = "DC",
  FL = "FL",
  GA = "GA",
  HI = "HI",
  ID = "ID",
  IL = "IL",
  IN = "IN",
  IA = "IA",
  KS = "KS",
  KY = "KY",
  LA = "LA",
  ME = "ME",
  MD = "MD",
  MA = "MA",
  MI = "MI",
  MN = "MN",
  MS = "MS",
  MO = "MO",
  MT = "MT",
  NE = "NE",
  NV = "NV",
  NH = "NH",
  NJ = "NJ",
  NM = "NM",
  NY = "NY",
  NC = "NC",
  ND = "ND",
  OH = "OH",
  OK = "OK",
  OR = "OR",
  PA = "PA",
  RI = "RI",
  SC = "SC",
  SD = "SD",
  TN = "TN",
  TX = "TX",
  UT = "UT",
  VT = "VT",
  VA = "VA",
  WA = "WA",
  WV = "WV",
  WI = "WI",
  WY = "WY",
}

export const states: Record<USState, string> = {
  [USState.AZ]: "Arizona",
  [USState.AL]: "Alabama",
  [USState.AK]: "Alaska",
  [USState.AR]: "Arkansas",
  [USState.CA]: "California",
  [USState.CO]: "Colorado",
  [USState.CT]: "Connecticut",
  [USState.DE]: "Delaware",
  [USState.DC]: "District of Columbia",
  [USState.FL]: "Florida",
  [USState.GA]: "Georgia",
  [USState.HI]: "Hawaii",
  [USState.ID]: "Idaho",
  [USState.IL]: "Illinois",
  [USState.IN]: "Indiana",
  [USState.IA]: "Iowa",
  [USState.KS]: "Kansas",
  [USState.KY]: "Kentucky",
  [USState.LA]: "Louisiana",
  [USState.ME]: "Maine",
  [USState.MD]: "Maryland",
  [USState.MA]: "Massachusetts",
  [USState.MI]: "Michigan",
  [USState.MN]: "Minnesota",
  [USState.MS]: "Mississippi",
  [USState.MO]: "Missouri",
  [USState.MT]: "Montana",
  [USState.NE]: "Nebraska",
  [USState.NV]: "Nevada",
  [USState.NH]: "New Hampshire",
  [USState.NJ]: "New Jersey",
  [USState.NM]: "New Mexico",
  [USState.NY]: "New York",
  [USState.NC]: "North Carolina",
  [USState.ND]: "North Dakota",
  [USState.OH]: "Ohio",
  [USState.OK]: "Oklahoma",
  [USState.OR]: "Oregon",
  [USState.PA]: "Pennsylvania",
  [USState.RI]: "Rhode Island",
  [USState.SC]: "South Carolina",
  [USState.SD]: "South Dakota",
  [USState.TN]: "Tennessee",
  [USState.TX]: "Texas",
  [USState.UT]: "Utah",
  [USState.VT]: "Vermont",
  [USState.VA]: "Virginia",
  [USState.WA]: "Washington",
  [USState.WV]: "West Virginia",
  [USState.WI]: "Wisconsin",
  [USState.WY]: "Wyoming",
};

export const stateToTimezone: Record<USState, string> = {
  [USState.AL]: "America/Chicago",
  [USState.AK]: "America/Anchorage",
  [USState.AZ]: "America/Phoenix",
  [USState.AR]: "America/Chicago",
  [USState.CA]: "America/Los_Angeles",
  [USState.CO]: "America/Denver",
  [USState.CT]: "America/New_York",
  [USState.DE]: "America/New_York",
  [USState.DC]: "America/New_York",
  [USState.FL]: "America/New_York",
  [USState.GA]: "America/New_York",
  [USState.HI]: "Pacific/Honolulu",
  [USState.ID]: "America/Boise", // Covers most of Idaho.
  [USState.IL]: "America/Chicago",
  [USState.IN]: "America/Indiana/Indianapolis", // Covers most of Indiana.
  [USState.IA]: "America/Chicago",
  [USState.KS]: "America/Chicago",
  [USState.KY]: "America/New_York",
  [USState.LA]: "America/Chicago",
  [USState.ME]: "America/New_York",
  [USState.MD]: "America/New_York",
  [USState.MA]: "America/New_York",
  [USState.MI]: "America/Detroit",
  [USState.MN]: "America/Chicago",
  [USState.MS]: "America/Chicago",
  [USState.MO]: "America/Chicago",
  [USState.MT]: "America/Denver",
  [USState.NE]: "America/Chicago",
  [USState.NV]: "America/Los_Angeles",
  [USState.NH]: "America/New_York",
  [USState.NJ]: "America/New_York",
  [USState.NM]: "America/Denver",
  [USState.NY]: "America/New_York",
  [USState.NC]: "America/New_York",
  [USState.ND]: "America/Chicago",
  [USState.OH]: "America/New_York",
  [USState.OK]: "America/Chicago",
  [USState.OR]: "America/Los_Angeles",
  [USState.PA]: "America/New_York",
  [USState.RI]: "America/New_York",
  [USState.SC]: "America/New_York",
  [USState.SD]: "America/Chicago",
  [USState.TN]: "America/Chicago",
  [USState.TX]: "America/Chicago",
  [USState.UT]: "America/Denver",
  [USState.VT]: "America/New_York",
  [USState.VA]: "America/New_York",
  [USState.WA]: "America/Los_Angeles",
  [USState.WV]: "America/New_York",
  [USState.WI]: "America/Chicago",
  [USState.WY]: "America/Denver",
};
