version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: production
      AWS_REGION: us-east-1
      TERMINOLOGY_BUCKET: umls-terminology
