version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8666:8080"
    environment:
      NODE_ENV: development
      AWS_REGION: us-east-2
      TERMINOLOGY_BUCKET: metriport-multi-purpose-staging
    volumes:
      - ./terminology_v2.2.db:/app/terminology_v2.2.db
