/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import * as MetriportApi from "../../../../../../api";
import * as core from "../../../../../../core";

export const Response: core.serialization.Schema<
    serializers.medical.converter.convertToFhir.Response.Raw,
    MetriportApi.medical.Cda[]
> = core.serialization.list(core.serialization.lazy(async () => (await import("../../../../..")).medical.Cda));

export declare namespace Response {
    type Raw = serializers.medical.Cda.Raw[];
}
