/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.devices.users.requests;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_EMPTY)
@JsonDeserialize(
    builder = GetMetriportUserIdRequest.Builder.class
)
public final class GetMetriportUserIdRequest {
  private final String appUserId;

  private GetMetriportUserIdRequest(String appUserId) {
    this.appUserId = appUserId;
  }

  /**
   * @return The user ID you identify this user with in your app.
   */
  @JsonProperty("appUserId")
  public String getAppUserId() {
    return appUserId;
  }

  @Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof GetMetriportUserIdRequest && equalTo((GetMetriportUserIdRequest) other);
  }

  private boolean equalTo(GetMetriportUserIdRequest other) {
    return appUserId.equals(other.appUserId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(this.appUserId);
  }

  @Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static AppUserIdStage builder() {
    return new Builder();
  }

  public interface AppUserIdStage {
    _FinalStage appUserId(String appUserId);

    Builder from(GetMetriportUserIdRequest other);
  }

  public interface _FinalStage {
    GetMetriportUserIdRequest build();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements AppUserIdStage, _FinalStage {
    private String appUserId;

    private Builder() {
    }

    @Override
    public Builder from(GetMetriportUserIdRequest other) {
      appUserId(other.getAppUserId());
      return this;
    }

    /**
     * <p>The user ID you identify this user with in your app.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @Override
    @JsonSetter("appUserId")
    public _FinalStage appUserId(String appUserId) {
      this.appUserId = appUserId;
      return this;
    }

    @Override
    public GetMetriportUserIdRequest build() {
      return new GetMetriportUserIdRequest(appUserId);
    }
  }
}
