/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import * as Metriport from "../../../../../../api";
import * as core from "../../../../../../core";

export const Addresses: core.serialization.Schema<serializers.medical.Addresses.Raw, Metriport.medical.Addresses> =
    core.serialization.undiscriminatedUnion([
        core.serialization.lazyObject(async () => (await import("../../../../..")).Address),
        core.serialization.list(core.serialization.lazyObject(async () => (await import("../../../../..")).Address)),
    ]);

export declare namespace Addresses {
    type Raw = serializers.Address.Raw | serializers.Address.Raw[];
}
