/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import * as Metriport from "../../../../../../api";
import * as core from "../../../../../../core";

export const Patient: core.serialization.ObjectSchema<serializers.medical.Patient.Raw, Metriport.medical.Patient> =
    core.serialization
        .object({
            id: core.serialization.string(),
        })
        .extend(core.serialization.lazyObject(async () => (await import("../../../../..")).medical.BasePatient));

export declare namespace Patient {
    interface Raw extends serializers.medical.BasePatient.Raw {
        id: string;
    }
}
