/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface MetriportUserIdResponse {
    /** The Metriport user ID to be used in subsequent requests for this user. */
    userId: string;
}
