import { z } from "zod";

// https://developer.withings.com/api-reference/#operation/measurev2-getworkouts
export const withingsWorkoutLogsResp = z.array(
  z.object({
    category: z.number(),
    timezone: z.string().optional().nullable(),
    model: z.number().optional().nullable(),
    attrib: z.number().optional().nullable(),
    startdate: z.number(),
    enddate: z.number(),
    date: z.string(),
    modified: z.number().optional().nullable(),
    deviceid: z.string().optional().nullable(),
    data: z
      .object({
        algo_pause_duration: z.number().optional().nullable(),
        calories: z.number().optional().nullable(),
        distance: z.number().optional().nullable(),
        elevation: z.number().optional().nullable(),
        hr_average: z.number().optional().nullable(),
        hr_max: z.number().optional().nullable(),
        hr_min: z.number().optional().nullable(),
        hr_zone_0: z.number().optional().nullable(),
        hr_zone_1: z.number().optional().nullable(),
        hr_zone_2: z.number().optional().nullable(),
        hr_zone_3: z.number().optional().nullable(),
        intensity: z.number().optional().nullable(),
        manual_calories: z.number().optional().nullable(),
        manual_distance: z.number().optional().nullable(),
        pause_duration: z.number().optional().nullable(),
        pool_laps: z.number().optional().nullable(),
        pool_length: z.number().optional().nullable(),
        spo2_average: z.number().optional().nullable(),
        steps: z.number().optional().nullable(),
        strokes: z.number().optional().nullable(),
      })
      .optional(),
  })
);

export type WithingsWorkoutLogs = z.infer<typeof withingsWorkoutLogsResp>;

export const categories: { [key: number]: string } = {
  1: "Walk",
  2: "Run",
  3: "Hiking",
  4: "Skating",
  5: "BMX",
  6: "Bicycling",
  7: "Swimming",
  8: "Surfing",
  9: "Kitesurfing",
  10: "Windsurfing",
  11: "Bodyboard",
  12: "Tennis",
  13: "Table tennis",
  14: "Squash",
  15: "Badminton",
  16: "Lift weights",
  17: "Calisthenics",
  18: "Elliptical",
  19: "Pilates",
  20: "Basket-ball",
  21: "Soccer",
  22: "Football",
  23: "Rugby",
  24: "Volley-ball",
  25: "Waterpolo",
  26: "Horse riding",
  27: "Golf",
  28: "Yoga",
  29: "Dancing",
  30: "Boxing",
  31: "Fencing",
  32: "Wrestling",
  33: "Martial arts",
  34: "Skiing",
  35: "Snowboarding",
  36: "Other",
  128: "No activity",
  187: "Rowing",
  188: "Zumba",
  191: "Baseball",
  192: "Handball",
  193: "Hockey",
  194: "Ice hockey",
  195: "Climbing",
  196: "Ice skating",
  272: "Multi-sport",
  306: "Indoor walk",
  307: "Indoor running",
  308: "Indoor cycling",
};
