version: "3.8"

name: fhir-to-csv

networks:
  metriportNetwork:
    name: metriportNetwork
    driver: bridge
services:
  fhir-to-csv:
    container_name: fhir-to-csv
    build:
      dockerfile: ./Dockerfile
    volumes:
      - .:/usr/app/data
    environment:
      ENV: ${ENV}
      AWS_REGION: ${AWS_REGION}
      CX_ID: ${CX_ID}
      API_URL: http://host.docker.internal:8080
      JOB_ID: ${JOB_ID}
      INPUT_S3_BUCKET: ${INPUT_S3_BUCKET}
      OUTPUT_S3_BUCKET: ${OUTPUT_S3_BUCKET}
      SNOWFLAKE_ACCOUNT: ${SNOWFLAKE_ACCOUNT}
      SNOWFLAKE_USER: ${SNOWFLAKE_USER}
      SNOWFLAKE_PASSWORD: ${SNOWFLAKE_PASSWORD}
      SNOWFLAKE_ROLE: ${SNOWFLAKE_ROLE}
      SNOWFLAKE_WAREHOUSE: ${SNOWFLAKE_WAREHOUSE}
      SNOWFLAKE_INTEGRATION: ${SNOWFLAKE_INTEGRATION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    networks:
      - metriportNetwork
