/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Telecommunications form for contact point - what communications system is required to make use of the contact.
 */
export type ContactPointSystem = "phone" | "fax" | "email" | "pager" | "url" | "sms" | "other";

export const ContactPointSystem = {
    Phone: "phone",
    Fax: "fax",
    Email: "email",
    Pager: "pager",
    Url: "url",
    Sms: "sms",
    Other: "other",
} as const;
