/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The direction of the sort, ascending or descending.
 */
export type DataRequirementSortDirection = "ascending" | "descending";

export const DataRequirementSortDirection = {
    Ascending: "ascending",
    Descending: "descending",
} as const;
