/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The units of time for the period in UCUM units.
 */
export type TimingRepeatPeriodUnit = "s" | "min" | "h" | "d" | "wk" | "mo" | "a";

export const TimingRepeatPeriodUnit = {
    S: "s",
    Min: "min",
    H: "h",
    D: "d",
    Wk: "wk",
    Mo: "mo",
    A: "a",
} as const;
