export const activityTypeMapping: Record<number, string> = {
  83: "Transition",
  82: "Swim Bike Run",
  300: "Other",
  56: "Wrestling",
  72: "Tai Chi",
  28: "Martial Arts",
  65: "Kickboxing",
  8: "Boxing",
  55: "Water Sports",
  54: "Water Polo",
  53: "Water Fitness",
  46: "Swimming",
  45: "Surfing Sports",
  38: "Sailing",
  35: "Rowing",
  31: "Paddle Sports",
  39: "Skating Sports",
  67: "Snowboarding",
  40: "Snow Sports",
  61: "Downhill Skiing",
  12: "Curling",
  60: "Cross Country Skiing",
  32: "Play",
  26: "Hunting",
  24: "Hiking",
  21: "Golf",
  19: "Fishing",
  17: "Equestrian Sports",
  9: "Climbing",
  48: "Tennis",
  47: "Table Tennis",
  43: "Squash",
  34: "Racquetball",
  79: "Pickleball",
  4: "Badminton",
  66: "Pilates",
  29: "Mind and Body",
  57: "Yoga",
  78: "Social Dance",
  77: "Cardio Dance",
  58: "Barre",
  76: "Fitness Gaming",
  69: "Step Training",
  68: "Stairs",
  44: "Stair Climbing",
  64: "Jump Rope",
  63: "High Intensity Interval Training",
  73: "Mixed Cardio",
  11: "Cross Training",
  50: "Traditional Strength Training",
  20: "Functional Strength Training",
  16: "Elliptical",
  59: "Core Training",
  74: "Hand Cycling",
  13: "Cycling",
  71: "Wheelchair Run Pace",
  70: "Wheelchair Walk Pace",
  37: "Running",
  52: "Walking",
  80: "Cooldown",
  62: "Flexibility",
  33: "Preparation and Recovery",
  51: "Volleyball",
  42: "Softball",
  41: "Soccer",
  36: "Rugby",
  27: "Lacrosse",
  25: "Hockey",
  23: "Handball",
  75: "Disc Sports",
  10: "Cricket",
  6: "Basketball",
  5: "Baseball",
  3: "Australian Football",
  1: "American Football",
  49: "Track and Field",
  22: "Gymnastics",
  18: "Fencing",
  7: "Bowling",
  2: "Archery",
};
