/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.medical.organization.types;

import java.lang.String;
import resources.commons.types.Address;

public interface IOrganizationCreate {
  String getName();

  OrgType getType();

  Address getLocation();
}
