/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.medical.organization.types;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.util.Objects;
import resources.commons.types.Address;

@JsonInclude(JsonInclude.Include.NON_EMPTY)
@JsonDeserialize(
    builder = OrganizationCreate.Builder.class
)
public final class OrganizationCreate implements IOrganizationCreate {
  private final String name;

  private final OrgType type;

  private final Address location;

  private OrganizationCreate(String name, OrgType type, Address location) {
    this.name = name;
    this.type = type;
    this.location = location;
  }

  /**
   * @return The name of your organization.
   * This is usually your legal corporate entity name -
   * for example <code>Metriport Inc.</code>.
   */
  @JsonProperty("name")
  @Override
  public String getName() {
    return name;
  }

  /**
   * @return The type of your organization.
   */
  @JsonProperty("type")
  @Override
  public OrgType getType() {
    return type;
  }

  @JsonProperty("location")
  @Override
  public Address getLocation() {
    return location;
  }

  @Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof OrganizationCreate && equalTo((OrganizationCreate) other);
  }

  private boolean equalTo(OrganizationCreate other) {
    return name.equals(other.name) && type.equals(other.type) && location.equals(other.location);
  }

  @Override
  public int hashCode() {
    return Objects.hash(this.name, this.type, this.location);
  }

  @Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static NameStage builder() {
    return new Builder();
  }

  public interface NameStage {
    TypeStage name(String name);

    Builder from(OrganizationCreate other);
  }

  public interface TypeStage {
    LocationStage type(OrgType type);
  }

  public interface LocationStage {
    _FinalStage location(Address location);
  }

  public interface _FinalStage {
    OrganizationCreate build();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements NameStage, TypeStage, LocationStage, _FinalStage {
    private String name;

    private OrgType type;

    private Address location;

    private Builder() {
    }

    @Override
    public Builder from(OrganizationCreate other) {
      name(other.getName());
      type(other.getType());
      location(other.getLocation());
      return this;
    }

    /**
     * <p>The name of your organization.
     * This is usually your legal corporate entity name -
     * for example <code>Metriport Inc.</code>.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @Override
    @JsonSetter("name")
    public TypeStage name(String name) {
      this.name = name;
      return this;
    }

    /**
     * <p>The type of your organization.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @Override
    @JsonSetter("type")
    public LocationStage type(OrgType type) {
      this.type = type;
      return this;
    }

    @Override
    @JsonSetter("location")
    public _FinalStage location(Address location) {
      this.location = location;
      return this;
    }

    @Override
    public OrganizationCreate build() {
      return new OrganizationCreate(name, type, location);
    }
  }
}
