/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as MetriportApi from "../../../../..";
import express from "express";
import * as serializers from "../../../../../../serialization";
import * as errors from "../../../../../../errors";

export interface ConverterServiceMethods {
    convertToFhir(
        req: express.Request<never, MetriportApi.medical.Cda[], MetriportApi.fhir.Bundle, never>,
        res: {
            send: (responseBody: MetriportApi.medical.Cda[]) => Promise<void>;
            cookie: (cookie: string, value: string, options?: express.CookieOptions) => void;
            locals: any;
        }
    ): void | Promise<void>;
}

export class ConverterService {
    private router;

    constructor(private readonly methods: ConverterServiceMethods, middleware: express.RequestHandler[] = []) {
        this.router = express.Router({ mergeParams: true }).use(
            express.json({
                strict: false,
            }),
            ...middleware
        );
    }

    public addMiddleware(handler: express.RequestHandler): this {
        this.router.use(handler);
        return this;
    }

    public toRouter(): express.Router {
        this.router.post("/convert-to-fhir", async (req, res, next) => {
            const request = await serializers.fhir.Bundle.parse(req.body);
            if (request.ok) {
                req.body = request.value;
                try {
                    await this.methods.convertToFhir(req as any, {
                        send: async (responseBody) => {
                            res.json(
                                await serializers.medical.converter.convertToFhir.Response.jsonOrThrow(responseBody, {
                                    unrecognizedObjectKeys: "strip",
                                })
                            );
                        },
                        cookie: res.cookie.bind(res),
                        locals: res.locals,
                    });
                    next();
                } catch (error) {
                    console.error(error);
                    if (error instanceof errors.MetriportApiError) {
                        switch (error.errorName) {
                            case "InvalidFhirError":
                                break;
                            default:
                                console.warn(
                                    `Endpoint 'convert-to-fhir' unexpectedly threw ${error.constructor.name}.` +
                                        ` If this was intentional, please add ${error.constructor.name} to` +
                                        " the endpoint's errors list in your Fern Definition."
                                );
                        }
                        await error.send(res);
                    } else {
                        res.status(500).json("Internal Server Error");
                    }
                    next(error);
                }
            } else {
                res.status(422).json({
                    errors: request.errors.map(
                        (error) => ["request", ...error.path].join(" -> ") + ": " + error.message
                    ),
                });
                next(request.errors);
            }
        });
        return this.router;
    }
}
