/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import * as Metriport from "../../../../../../api";
import * as core from "../../../../../../core";

export const ConnectTokenResponse: core.serialization.ObjectSchema<
    serializers.devices.ConnectTokenResponse.Raw,
    Metriport.devices.ConnectTokenResponse
> = core.serialization.object({
    token: core.serialization.string(),
});

export declare namespace ConnectTokenResponse {
    interface Raw {
        token: string;
    }
}
