#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

changed() {
  git diff --name-only HEAD@{1} HEAD | grep "$1" > /dev/null 2>&1
}

echo "Checking updates on package.json files..."

if changed 'package.json'; then
  echo " "
  echo "⚠  One or more package.json changed. You should run 'npm install' on the root/respective folder"
  echo " "
else
  echo "No updates detected on package.json files."
fi

echo "Checking updates on DB migration files..."

if changed 'packages/api/src/sequelize/migrations'; then
  echo " "
  echo "⚠  DB updates detected. You should run 'npm run db-local:up' on ./packages/api"
  echo " "
else
  echo "No DB updates detected."
fi
