/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type OrgType = "acuteCare" | "ambulatory" | "hospital" | "labSystems" | "pharmacy" | "postAcuteCare";

export const OrgType = {
    AcuteCare: "acuteCare",
    Ambulatory: "ambulatory",
    Hospital: "hospital",
    LabSystems: "labSystems",
    Pharmacy: "pharmacy",
    PostAcuteCare: "postAcuteCare",
} as const;
