export const MAX_SQS_MESSAGE_SIZE = 246000;
export const SQS_MESSAGE_BATCH_SIZE_FIFO = 250;
export const SQS_MESSAGE_BATCH_SIZE_STANDARD = 2500;
export const SQS_MESSAGE_BATCH_MILLIS_TO_SLEEP = 1000;
