/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Metriport from "../../../../api";
import * as core from "../../../../core";

export const Aminos: core.serialization.ObjectSchema<serializers.devices.Aminos.Raw, Metriport.devices.Aminos> =
    core.serialization.object({
        alanineG: core.serialization.property("alanine_g", core.serialization.number().optional()),
        arginineG: core.serialization.property("arginine_g", core.serialization.number().optional()),
        asparagineG: core.serialization.property("asparagine_g", core.serialization.number().optional()),
        asparticAcidG: core.serialization.property("aspartic_acid_g", core.serialization.number().optional()),
        cysteineG: core.serialization.property("cysteine_g", core.serialization.number().optional()),
        glutamineG: core.serialization.property("glutamine_g", core.serialization.number().optional()),
        glutamicAcidG: core.serialization.property("glutamic_acid_g", core.serialization.number().optional()),
        glycineG: core.serialization.property("glycine_g", core.serialization.number().optional()),
        histidineG: core.serialization.property("histidine_g", core.serialization.number().optional()),
        isoleucineG: core.serialization.property("isoleucine_g", core.serialization.number().optional()),
        leucineG: core.serialization.property("leucine_g", core.serialization.number().optional()),
        lysineG: core.serialization.property("lysine_g", core.serialization.number().optional()),
        methionineG: core.serialization.property("methionine_g", core.serialization.number().optional()),
        phenylalanineG: core.serialization.property("phenylalanine_g", core.serialization.number().optional()),
        prolineG: core.serialization.property("proline_g", core.serialization.number().optional()),
        serineG: core.serialization.property("serine_g", core.serialization.number().optional()),
        threonineG: core.serialization.property("threonine_g", core.serialization.number().optional()),
        tryptophanG: core.serialization.property("tryptophan_g", core.serialization.number().optional()),
        tyrosineG: core.serialization.property("tyrosine_g", core.serialization.number().optional()),
        valineG: core.serialization.property("valine_g", core.serialization.number().optional()),
    });

export declare namespace Aminos {
    interface Raw {
        alanine_g?: number | null;
        arginine_g?: number | null;
        asparagine_g?: number | null;
        aspartic_acid_g?: number | null;
        cysteine_g?: number | null;
        glutamine_g?: number | null;
        glutamic_acid_g?: number | null;
        glycine_g?: number | null;
        histidine_g?: number | null;
        isoleucine_g?: number | null;
        leucine_g?: number | null;
        lysine_g?: number | null;
        methionine_g?: number | null;
        phenylalanine_g?: number | null;
        proline_g?: number | null;
        serine_g?: number | null;
        threonine_g?: number | null;
        tryptophan_g?: number | null;
        tyrosine_g?: number | null;
        valine_g?: number | null;
    }
}
