/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Metriport from "../../../../api";
import * as core from "../../../../core";

export const MetriportData: core.serialization.ObjectSchema<
    serializers.devices.MetriportData.Raw,
    Metriport.devices.MetriportData
> = core.serialization.object({
    metadata: core.serialization.lazyObject(async () => (await import("../../..")).devices.Metadata),
});

export declare namespace MetriportData {
    interface Raw {
        metadata: serializers.devices.Metadata.Raw;
    }
}
