/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Metriport from "../../../../api";
import * as core from "../../../../core";

export const Micros: core.serialization.ObjectSchema<serializers.devices.Micros.Raw, Metriport.devices.Micros> =
    core.serialization.object({
        biotinMg: core.serialization.property("biotin_mg", core.serialization.number().optional()),
        caffeineMg: core.serialization.property("caffeine_mg", core.serialization.number().optional()),
        calciumMg: core.serialization.property("calcium_mg", core.serialization.number().optional()),
        copperMg: core.serialization.property("copper_mg", core.serialization.number().optional()),
        folateMg: core.serialization.property("folate_mg", core.serialization.number().optional()),
        folicAcidMg: core.serialization.property("folic_acid_mg", core.serialization.number().optional()),
        iodineMg: core.serialization.property("iodine_mg", core.serialization.number().optional()),
        ironMg: core.serialization.property("iron_mg", core.serialization.number().optional()),
        magnesiumMg: core.serialization.property("magnesium_mg", core.serialization.number().optional()),
        manganeseMg: core.serialization.property("manganese_mg", core.serialization.number().optional()),
        phosphorusMg: core.serialization.property("phosphorus_mg", core.serialization.number().optional()),
        potassiumMg: core.serialization.property("potassium_mg", core.serialization.number().optional()),
        seleniumMg: core.serialization.property("selenium_mg", core.serialization.number().optional()),
        vitaminAMg: core.serialization.property("vitamin_A_mg", core.serialization.number().optional()),
        vitaminB1Mg: core.serialization.property("vitamin_B1_mg", core.serialization.number().optional()),
        vitaminB2Mg: core.serialization.property("vitamin_B2_mg", core.serialization.number().optional()),
        vitaminB3Mg: core.serialization.property("vitamin_B3_mg", core.serialization.number().optional()),
        vitaminB5Mg: core.serialization.property("vitamin_B5_mg", core.serialization.number().optional()),
        vitaminB6Mg: core.serialization.property("vitamin_B6_mg", core.serialization.number().optional()),
        vitaminB12Mg: core.serialization.property("vitamin_B12_mg", core.serialization.number().optional()),
        vitaminCMg: core.serialization.property("vitamin_C_mg", core.serialization.number().optional()),
        vitaminDMg: core.serialization.property("vitamin_D_mg", core.serialization.number().optional()),
        vitaminEMg: core.serialization.property("vitamin_E_mg", core.serialization.number().optional()),
        vitaminKMg: core.serialization.property("vitamin_K_mg", core.serialization.number().optional()),
        zincMg: core.serialization.property("zinc_mg", core.serialization.number().optional()),
    });

export declare namespace Micros {
    interface Raw {
        biotin_mg?: number | null;
        caffeine_mg?: number | null;
        calcium_mg?: number | null;
        copper_mg?: number | null;
        folate_mg?: number | null;
        folic_acid_mg?: number | null;
        iodine_mg?: number | null;
        iron_mg?: number | null;
        magnesium_mg?: number | null;
        manganese_mg?: number | null;
        phosphorus_mg?: number | null;
        potassium_mg?: number | null;
        selenium_mg?: number | null;
        vitamin_A_mg?: number | null;
        vitamin_B1_mg?: number | null;
        vitamin_B2_mg?: number | null;
        vitamin_B3_mg?: number | null;
        vitamin_B5_mg?: number | null;
        vitamin_B6_mg?: number | null;
        vitamin_B12_mg?: number | null;
        vitamin_C_mg?: number | null;
        vitamin_D_mg?: number | null;
        vitamin_E_mg?: number | null;
        vitamin_K_mg?: number | null;
        zinc_mg?: number | null;
    }
}
