/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Metriport from "../../../../api";
import * as core from "../../../../core";

export const ProviderSource: core.serialization.Schema<
    serializers.devices.ProviderSource.Raw,
    Metriport.devices.ProviderSource
> = core.serialization.enum_([
    "apple",
    "cronometer",
    "dexcom",
    "fitbit",
    "garmin",
    "google",
    "oura",
    "tenovi",
    "whoop",
    "withings",
]);

export declare namespace ProviderSource {
    type Raw =
        | "apple"
        | "cronometer"
        | "dexcom"
        | "fitbit"
        | "garmin"
        | "google"
        | "oura"
        | "tenovi"
        | "whoop"
        | "withings";
}
