/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Metriport from "../../../../api";
import * as core from "../../../../core";

export const SourceType: core.serialization.Schema<serializers.devices.SourceType.Raw, Metriport.devices.SourceType> =
    core.serialization.enum_(["MANUAL_ENTRY", "DEVICE"]);

export declare namespace SourceType {
    type Raw = "MANUAL_ENTRY" | "DEVICE";
}
