/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Metriport from "../../../../api";
import * as core from "../../../../core";

export const Speed: core.serialization.ObjectSchema<serializers.devices.Speed.Raw, Metriport.devices.Speed> =
    core.serialization.object({
        maxKmH: core.serialization.property("max_km_h", core.serialization.number().optional()),
        avgKmH: core.serialization.property("avg_km_h", core.serialization.number().optional()),
    });

export declare namespace Speed {
    interface Raw {
        max_km_h?: number | null;
        avg_km_h?: number | null;
    }
}
