import * as dotenv from "dotenv";
dotenv.config();
// keep that ^ on top

import { Command } from "commander";
import { isAiBriefModel } from "@metriport/core/command/ai-brief/shared";
import { displayInColumns, samplePatientIds } from "./shared/utils";
import { generateAiSummary } from "./shared/generate-summary";
import { eachPatient } from "./shared/patient-iterator";

/**
 * Compares existing AI summaries against new AI summaries generated by the given LLM models. This
 * script will output the summary comparisons directly into the console - for a better HTML interface,
 * use the compare-report command.
 *
 * Example usage:
 * npm run summary -- compare-existing --cx-id <cxId> --model "openai.gpt-oss-120b-1:0" --total-patients <totalPatients>
 */
const command = new Command();
command.name("compare-existing");
command.description("Compares existing AI summaries across different models");
command.requiredOption("--cx-id <cxId>", "The ID of the customer");
command.option("--total-patients <totalPatients>", "The total number of patients to compare", "10");
command.option(
  "--model <model>",
  "The model to use for the comparison (claude-sonnet-3.5, openai.gpt-oss-120b-1:0)",
  "openai.gpt-oss-120b-1:0"
);
command.action(compareExistingAiSummaries);

async function compareExistingAiSummaries({
  cxId,
  model,
  totalPatients,
}: {
  cxId: string;
  model: string;
  totalPatients: string;
}) {
  if (!isAiBriefModel(model)) {
    throw new Error(`Invalid model: ${model}`);
  }

  const patientIds = await samplePatientIds(cxId, totalPatients);
  for await (const { patientId, consolidatedBundle, existingAiSummary } of eachPatient(
    cxId,
    patientIds
  )) {
    if (!consolidatedBundle) {
      console.log(`No consolidated bundle found for patient ${patientId}`);
      continue;
    }
    if (!existingAiSummary) {
      console.log(`No existing AI summary found for patient ${patientId}`);
      continue;
    }

    console.log(`Comparing ${model} summary for patient ${patientId}`);
    const { summary: comparisonSummary, durationInMs } = await generateAiSummary({
      bundle: consolidatedBundle,
      cxId,
      patientId,
      model,
    });
    displayInColumns(existingAiSummary, comparisonSummary);
    console.log(`${model} - summary generation took ${(durationInMs / 1000).toFixed(2)} seconds`);
  }
}

export default command;
