import * as dotenv from "dotenv";
dotenv.config();
// keep that ^ on top

import { Command } from "commander";
import { Config } from "@metriport/core/util/config";
import { FeatureFlags } from "@metriport/core/command/feature-flags/ffs-on-dynamodb";
import compareExisting from "./compare-existing";
import comparePatient from "./compare-patient";
import compareReport from "./compare-report";
import compareRerun from "./compare-rerun";

/**
 * This is the main command registry for AI summarization utilities. You should add any new
 * commands to this registry, and ensure that your command has a unique name.
 *
 * These utilities are used for creating comparison reports of AI summaries across different LLM
 * providers and prompting strategies. Currently, there are only commands for comparing existing
 * AI summaries generated by Claude against those generated by GPT-OSS-120B. This can be extended
 * to compare against other providers and prompting strategies in the future.
 */
const program = new Command();
FeatureFlags.init(Config.getAWSRegion(), Config.getFeatureFlagsTableName());

program.name("summary");
program.description(
  "Scripts for comparing AI summarization across different LLM providers and prompting strategies"
);
program.addCommand(compareExisting);
program.addCommand(comparePatient);
program.addCommand(compareReport);
program.addCommand(compareRerun);
program.parse(process.argv);
