name: "core_transform"
version: "1.0.0"
config-version: 2

profile: "core_transform"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  input_database: db
  input_schema: schema
  custom_bucket_name: tuva-public-resources

models:
  core_transform:
    core_pipeline:
      stage:
        +materialized: view
      core:
        +schema: core
        +materialized: table
