name: "core_transform"
version: "1.0.0"
config-version: 2

profile: "core_transform"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  input_database: db
  input_schema: schema
  input_job_id: job_id
  full_refresh: false
  lookback_timestamp: "1970-01-01 00:00:00"

models:
  core_transform:
    core_pipeline:
      stage:
        +schema: stage
        +materialized: view

      core:
        +schema: core
        +materialized: "{{ 'table' if (var('full_refresh', false) == true or (var('full_refresh', false) is string and var('full_refresh', false)|lower == 'true')) else 'incremental' }}"
        +incremental_strategy: delete+insert
        +on_schema_change: append_new_columns
