name: "core_transform"
version: "1.0.0"
config-version: 2

profile: "core_transform"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
docs-paths: ["dbt_doc_blocks"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  input_database: db
  input_schema: schema
  clinical_enabled: true
  cms_hcc_payment_year: 2023
  quality_measures_period_end: "2023-12-31"
  tuva_last_run: '{{ run_started_at.astimezone(modules.pytz.timezone("UTC")) }}'
  custom_bucket_name: tuva-public-resources

models:
  core_transform:
    core_pipeline:
      stage:
        +materialized: ephemeral
      intermediate:
        +materialized: ephemeral
      core:
        +schema: core_v2
        +materialized: table
