name: Reusable Build workflow

on:
  workflow_call:
    inputs:
      path:
        required: true
        type: string
        description: "sub-directory where this workflow should execute lint and build "
      treat-as-package:
        required: false
        type: boolean
        default: true
        description: "whether this workflow should 'npm ci' on parent folder, 'input.path' if false (default=true)"
      build_env:
        required: false
        type: string
        description: "the environment we're building to, either 'staging' or 'production'"
        default: "production"
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  lint-build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Runner/env info
        run: |
          echo "Runner name: $RUNNER_NAME"
          echo "Runner OS: $RUNNER_OS"
          uname -a
          echo "Memory info:"
          free -h || cat /proc/meminfo
          echo "Node / npm versions:"
          node -v
          npm -v
          echo "Env NODE_OPTIONS=$NODE_OPTIONS"
          env

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: "18.14"
      - name: Checkout
        uses: actions/checkout@v3
      - name: Log Git Ref
        run: |
          echo "Git ref: $(git rev-parse HEAD)"
        shell: bash

      # run even when treat-as-package is false b/c of inter-package dependencies
      - name: Install on root
        env:
          NODE_OPTIONS: --max_old_space_size=4096
        run: |
          pwd
          npm run install-deps
        working-directory: "./" # from root bc package-lock.json is there

      - name: Run Linter
        run: npm run lint
        working-directory: ${{ inputs.path }}
      # move to an external file so both this and deploy can use this logic

      # run even when treat-as-package is false b/c of inter-package dependencies
      - name: Build/compile on root
        if: ${{ inputs.build_env == 'production' }}
        env:
          NODE_OPTIONS: --max_old_space_size=4096
        run: |
          pwd
          npm run build:cloud
        working-directory: "./"
      # run even when treat-as-package is false b/c of inter-package dependencies
      - name: Build/compile on root STAGING
        if: ${{ inputs.build_env == 'staging' }}
        env:
          NODE_OPTIONS: --max_old_space_size=4096
        run: |
          pwd
          npm run build:staging
        working-directory: "./"

      - name: Build/compile on sub-folder/package
        if: ${{ inputs.treat-as-package == false }}
        env:
          NODE_OPTIONS: --max_old_space_size=4096
        run: |
          pwd
          npm run build:cloud
        working-directory: ${{ inputs.path }}

      - name: Run Tests
        env:
          NODE_OPTIONS: --max_old_space_size=4096
        run: npm run test
        working-directory: ${{ inputs.path }}
