name: Reusable Deploy workflow for API

on:
  workflow_call:
    inputs:
      deploy_env:
        description: "the environment we're deploying to, either 'staging', 'production', or 'sandbox'"
        required: true
        type: string
      script_name:
        description: "the name of the script under the scripts/ folder to run"
        required: false
        type: string
        default: "deploy-analytics-platform.sh"
      ECR_REPO_URI:
        description: "The URI of the ECR repository to push the Docker image to"
        required: true
        type: string
      AWS_REGION:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      SENTRY_AUTH_TOKEN:
        required: false
      SENTRY_ORG:
        required: false
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  deploy:
    # prevents 2+ devs/workflows trying to deploy to AWS at the same time
    # https://serverlessfirst.com/emails/how-to-prevent-concurrent-deployments-of-serverless-stacks-in-github-actions/
    # TODO Consider the solution here: https://github.com/tj-actions/aws-cdk/blob/main/action.yml
    concurrency:
      group: ${{ format('{0}-{1}', inputs.script_name, inputs.deploy_env) }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.deploy_env }}
    steps:
      - name: Log Environment
        run: |
          env
          echo "ECR_REPO_URI: ${{ inputs.ECR_REPO_URI }}"
          echo "AWS_REGION: ${{ inputs.AWS_REGION }}"
        shell: bash
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v3
      - name: Log Git Ref
        run: |
          echo "Git ref: $(git rev-parse HEAD)"
        shell: bash

      - name: Setup AWS CLI
        run: |
          aws configure set aws_access_key_id "${{ secrets.AWS_ACCESS_KEY_ID }}"
          aws configure set aws_secret_access_key "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          aws configure set default.region "${{ inputs.AWS_REGION }}"
        working-directory: "./"

      - name: Setup Docker
        run: docker buildx create --use
        working-directory: "./"

      - name: Deploy
        run: |
          ./packages/scripts/${{ inputs.script_name }}
        working-directory: "./"
        env:
          ECR_REPO_URI: ${{ inputs.ECR_REPO_URI }}
          AWS_REGION: ${{ inputs.AWS_REGION }}
