name: Reusable Deploy workflow based on CDK

on:
  workflow_call:
    inputs:
      build_env:
        description: "the environment we're building to, either 'staging' or 'production' - only apps that have special build scripts need to set this"
        type: string
        required: false
        default: "production"
      deploy_env:
        required: true
        type: string
        description: "the environment we're deploying to, either 'staging', 'production', or 'sandbox'"
      cdk_stack:
        required: true
        type: string
        description: "the name of the CDK stack we're deploying"
      add_sentry_release:
        description: "the name of the CDK stack we're deploying"
        required: false
        type: string
        default: "false"
      is-branch-to-staging:
        required: false
        type: boolean
        default: false
        description: "whether this workflow should checkout internal's develop/master or a feature branch"
      AWS_REGION:
        required: true
        type: string
      INFRA_CONFIG:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      SENTRY_AUTH_TOKEN:
        required: false
      SENTRY_ORG:
        required: false
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true
      SERVICE_PAT:
        required: true

jobs:
  deploy:
    # prevents 2+ devs/workflows trying to deploy to AWS at the same time
    # https://serverlessfirst.com/emails/how-to-prevent-concurrent-deployments-of-serverless-stacks-in-github-actions/
    # TODO Consider the solution here: https://github.com/tj-actions/aws-cdk/blob/main/action.yml
    concurrency:
      group: ${{ format('{0}-{1}-{2}', github.job, inputs.cdk_stack, inputs.deploy_env) }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.deploy_env }}
    steps:
      - name: Log Environment
        run: |
          env
        shell: bash
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: "18.14"

      # checkout the actual repo
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: metriport

      # checkout the internal repo to get configs - default branches
      - name: Checkout internal default branch
        uses: actions/checkout@v3
        if: ${{ inputs.is-branch-to-staging == false }}
        with:
          repository: metriport/metriport-internal
          ref: ${{ (inputs.deploy_env == 'production' || inputs.deploy_env == 'sandbox') && 'master' || 'develop' }}
          token: ${{ secrets.SERVICE_PAT }} # secret token from user 'metriport-service'
          path: metriport-internal
          sparse-checkout: |
            config-oss/api-infra
      # checkout the internal repo to get configs - feature branch when "branching to staging"
      - name: Determine which internal branch to checkout
        env:
          GITHUB_TOKEN: ${{ secrets.SERVICE_PAT }}
        run: |
          set +e # don't stop on failure
          gh api /repos/metriport/metriport-internal/branches/${{ github.ref_name }} --silent
          RESULT=$?
          if [ $RESULT -eq 0 ]; then
            INTERNAL_BRANCH=${{ github.ref }}
          else
            INTERNAL_BRANCH=develop
          fi
          echo "Internal branch for checkout: $INTERNAL_BRANCH"
          echo "INTERNAL_BRANCH=$INTERNAL_BRANCH" >> $GITHUB_ENV
      - name: Checkout internal feature branch
        uses: actions/checkout@v3
        if: ${{ inputs.is-branch-to-staging == true }}
        with:
          repository: metriport/metriport-internal
          ref: ${{ env.INTERNAL_BRANCH }}
          token: ${{ secrets.SERVICE_PAT }} # secret token from user 'metriport-service'
          path: metriport-internal
          sparse-checkout: |
            config-oss/api-infra

      - name: Log Git Ref
        run: |
          echo "Git ref: $(git rev-parse HEAD)"
        working-directory: metriport
        shell: bash

      # INSTALL DEPENDENCIES
      - name: Install root dependencies
        run: npm run install-deps
        working-directory: "metriport/"
      # ideally would only build what's needed, the connect-widget for one takes a long time and its not used by the lambdas nor infra
      - name: Build root dependencies
        run: npm run build:cloud
        working-directory: "metriport/"
      - name: Lambdas build shared layer
        run: npm run prep-deploy
        working-directory: "metriport/packages/lambdas/"

      # BUILD
      - name: Infra build/compile
        run: npm run build:cloud
        working-directory: "metriport/packages/infra"

      # TESTS
      - name: Infra test
        run: npm run test
        working-directory: "metriport/packages/infra"

        # SENTRY
      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
        # TODO: #156 disabled bc its not working, waiting Sentry support
        # https://metriport.slack.com/archives/C04FZ9859FZ/p1680112432771159?thread_ts=1680110062.829999&cid=C04FZ9859FZ
        # if: env.SENTRY_AUTH_TOKEN != null && env.SENTRY_ORG != null && inputs.add_sentry_release == 'true'
        if: false
        with:
          environment: ${{ inputs.deploy_env }}
          version: ${{ github.sha }}
          ignore_missing: true
          ignore_empty: true
          sourcemaps: metriport/packages/lambdas/dist
          projects: lambdas-oss

      # CDK DIFF
      - name: Diff CDK stack
        uses: metriport/deploy-with-cdk@master
        with:
          cdk_action: "diff"
          cdk_version: "2.87.0"
          cdk_stack: "${{ inputs.cdk_stack }}"
          cdk_env: "${{ inputs.deploy_env }}"
        env:
          INPUT_PATH: "metriport/packages/infra"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ inputs.AWS_REGION }}

      # DEPLOY
      - name: Deploy CDK stack
        uses: metriport/deploy-with-cdk@master
        with:
          cdk_action: "deploy --verbose --require-approval never"
          cdk_version: "2.87.0"
          cdk_stack: "${{ inputs.cdk_stack }}"
          cdk_env: "${{ inputs.deploy_env }}"
        env:
          INPUT_PATH: "metriport/packages/infra"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ inputs.AWS_REGION }}
          METRIPORT_VERSION: ${{ github.sha }}
