name: Re-deploy API Gateway

on:
  workflow_call:
    inputs:
      deploy_env:
        required: true
        type: string
        description: "the environment we're DEPLOYING to, either 'staging', 'production', or 'sandbox'"
      AWS_REGION:
        required: true
        type: string
        description: "the AWS region we're deploying to"
      API_GW_ID:
        required: true
        type: string
        description: "the API Gateway ID to redeploy after CDK deployment"
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  redeploy-api-gw:
    runs-on: ubuntu-latest
    environment: ${{ inputs.deploy_env }}
    steps:
      - name: Log Environment
        run: |
          env
        shell: bash

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: If branch to staging, rebase against develop
        uses: ./.github/actions/rebase-develop

      - name: Re-deploy API GW
        run: |
          ./packages/scripts/redeploy-api-gateway.sh
        shell: bash
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ inputs.AWS_REGION }}
          API_GW_ID: ${{ inputs.API_GW_ID }}