name: PR Check - Shared

on:
  pull_request:
    paths:
      - "packages/shared/**"
  merge_group:
  workflow_dispatch:

jobs:
  check-commits:
    uses: ./.github/workflows/_check-commits.yml
    secrets: inherit
  check-pr:
    uses: ./.github/workflows/_build.yml
    with:
      path: "packages/shared"
    secrets: inherit
