# Just marks the required checks as successful so PRs can be merged
# It should only run if there are no changes on the regular packages
name: PR Check - Others

on:
  pull_request:
  merge_group:
  workflow_dispatch:

jobs:
  files-changed:
    name: Detect changes on packages
    runs-on: ubuntu-latest
    timeout-minutes: 3
    # Map a step output to a job output
    outputs:
      packages: ${{ steps.changes.outputs.packages }}
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Detect Changes
        uses: dorny/paths-filter@4067d885736b84de7c414f582ac45897079b0a78 # v2
        id: changes
        with:
          filters: |
            packages:
              - "packages/api/**"
              - "packages/api-sdk/**"
              - "packages/carequality-cert-runner/**"
              - "packages/carequality-sdk/**"
              - "packages/commonwell-cert-runner/**"
              - "packages/commonwell-jwt-maker/**"
              - "packages/commonwell-sdk/**"
              - "packages/connect-widget/**"
              - "packages/core/**"
              - "packages/ihe-gateway-sdk/**"
              - "packages/infra/**"
              - "packages/lambdas/**"
              - "packages/shared/**"
              - "packages/utils/**"

  check-pr:
    needs: files-changed
    if: needs.files-changed.outputs.packages != 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Mark check-pr as successful
        run: |
          echo "Not running any checks, just marking 'check-pr' as successful"

  not-running:
    needs: files-changed
    if: needs.files-changed.outputs.packages == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Not running
        run: |
          echo "NOT making changes to the 'check-pr' status"
