name: Restart API - Sandbox

on:
  workflow_dispatch:

jobs:
  restart:
    uses: ./.github/workflows/_restart-ecs.yml
    with:
      deploy_env: "sandbox"
      ECR_REPO_URI: ${{ vars.ECR_REPO_URI_MLLP_SERVER_SANDBOX }}
      ECS_CLUSTER: ${{ vars.ECS_CLUSTER_MLLP_SERVER_SANDBOX }}
      ECS_SERVICE: ${{ vars.ECS_SERVICE_MLLP_SERVER_SANDBOX }}
      AWS_REGION: ${{ vars.API_REGION_SANDBOX }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
