/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Metriport from "../../../../..";

/**
 * @example
 *     {
 *         status: Metriport.medical.PatientConsolidatedDataStatus.Completed,
 *         message: "Trigger a new query by POST /patient/:id/consolidated/query; data will be sent through Webhook"
 *     }
 */
export interface GetConsolidatedQueryStatusResponse {
    status: Metriport.medical.PatientConsolidatedDataStatus;
    message?: string;
}
