/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Metriport from "../../../../..";

export interface StartConsolidatedQueryResponse {
    status: Metriport.medical.PatientConsolidatedDataStatus;
}
