/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as MetriportApi from "../../../../api";
import * as core from "../../../../core";

export const BundleSearch: core.serialization.ObjectSchema<
    serializers.fhir.BundleSearch.Raw,
    MetriportApi.fhir.BundleSearch
> = core.serialization.object({
    id: core.serialization.string().optional(),
    extension: core.serialization
        .list(core.serialization.lazyObject(async () => (await import("../../..")).fhir.Extension))
        .optional(),
    modifierExtension: core.serialization
        .list(core.serialization.lazyObject(async () => (await import("../../..")).fhir.Extension))
        .optional(),
    mode: core.serialization.lazy(async () => (await import("../../..")).fhir.BundleSearchMode).optional(),
    score: core.serialization.lazy(async () => (await import("../../..")).fhir.Decimal).optional(),
});

export declare namespace BundleSearch {
    interface Raw {
        id?: string | null;
        extension?: serializers.fhir.Extension.Raw[] | null;
        modifierExtension?: serializers.fhir.Extension.Raw[] | null;
        mode?: serializers.fhir.BundleSearchMode.Raw | null;
        score?: serializers.fhir.Decimal.Raw | null;
    }
}
