/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as MetriportApi from "../../../../api";
import * as core from "../../../../core";

export const BundleLink: core.serialization.ObjectSchema<
    serializers.fhir.BundleLink.Raw,
    MetriportApi.fhir.BundleLink
> = core.serialization.object({
    id: core.serialization.string().optional(),
    extension: core.serialization
        .list(core.serialization.lazyObject(async () => (await import("../../..")).fhir.Extension))
        .optional(),
    modifierExtension: core.serialization
        .list(core.serialization.lazyObject(async () => (await import("../../..")).fhir.Extension))
        .optional(),
    relation: core.serialization.string().optional(),
    url: core.serialization.lazy(async () => (await import("../../..")).fhir.Uri).optional(),
});

export declare namespace BundleLink {
    interface Raw {
        id?: string | null;
        extension?: serializers.fhir.Extension.Raw[] | null;
        modifierExtension?: serializers.fhir.Extension.Raw[] | null;
        relation?: string | null;
        url?: serializers.fhir.Uri.Raw | null;
    }
}
