/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as MetriportApi from "../../../../api";
import * as core from "../../../../core";

export const Code: core.serialization.Schema<serializers.fhir.Code.Raw, MetriportApi.fhir.Code> =
    core.serialization.string();

export declare namespace Code {
    type Raw = string;
}
