/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as MetriportApi from "../../../../api";
import * as core from "../../../../core";

export const Coding: core.serialization.ObjectSchema<serializers.fhir.Coding.Raw, MetriportApi.fhir.Coding> =
    core.serialization.object({
        id: core.serialization.string().optional(),
        extension: core.serialization
            .list(core.serialization.lazyObject(async () => (await import("../../..")).fhir.Extension))
            .optional(),
        system: core.serialization.lazy(async () => (await import("../../..")).fhir.Uri).optional(),
        version: core.serialization.string().optional(),
        code: core.serialization.lazy(async () => (await import("../../..")).fhir.Code).optional(),
        display: core.serialization.string().optional(),
        userSelected: core.serialization.boolean().optional(),
    });

export declare namespace Coding {
    interface Raw {
        id?: string | null;
        extension?: serializers.fhir.Extension.Raw[] | null;
        system?: serializers.fhir.Uri.Raw | null;
        version?: string | null;
        code?: serializers.fhir.Code.Raw | null;
        display?: string | null;
        userSelected?: boolean | null;
    }
}
