/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as MetriportApi from "../../../../api";
import * as core from "../../../../core";

export const ContactPointSystem: core.serialization.Schema<
    serializers.fhir.ContactPointSystem.Raw,
    MetriportApi.fhir.ContactPointSystem
> = core.serialization.enum_(["phone", "fax", "email", "pager", "url", "sms", "other"]);

export declare namespace ContactPointSystem {
    type Raw = "phone" | "fax" | "email" | "pager" | "url" | "sms" | "other";
}
