/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as MetriportApi from "../../../../api";
import * as core from "../../../../core";

export const DataRequirementSort: core.serialization.ObjectSchema<
    serializers.fhir.DataRequirementSort.Raw,
    MetriportApi.fhir.DataRequirementSort
> = core.serialization.object({
    id: core.serialization.string().optional(),
    extension: core.serialization
        .list(core.serialization.lazyObject(async () => (await import("../../..")).fhir.Extension))
        .optional(),
    modifierExtension: core.serialization
        .list(core.serialization.lazyObject(async () => (await import("../../..")).fhir.Extension))
        .optional(),
    path: core.serialization.string().optional(),
    direction: core.serialization
        .lazy(async () => (await import("../../..")).fhir.DataRequirementSortDirection)
        .optional(),
});

export declare namespace DataRequirementSort {
    interface Raw {
        id?: string | null;
        extension?: serializers.fhir.Extension.Raw[] | null;
        modifierExtension?: serializers.fhir.Extension.Raw[] | null;
        path?: string | null;
        direction?: serializers.fhir.DataRequirementSortDirection.Raw | null;
    }
}
