/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as MetriportApi from "../../../../api";
import * as core from "../../../../core";

export const DateTime: core.serialization.Schema<serializers.fhir.DateTime.Raw, MetriportApi.fhir.DateTime> =
    core.serialization.string();

export declare namespace DateTime {
    type Raw = string;
}
