/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as MetriportApi from "../../../../api";
import * as core from "../../../../core";

export const DistanceComparator: core.serialization.Schema<
    serializers.fhir.DistanceComparator.Raw,
    MetriportApi.fhir.DistanceComparator
> = core.serialization.enum_(["<", "<=", ">=", ">"]);

export declare namespace DistanceComparator {
    type Raw = "<" | "<=" | ">=" | ">";
}
