/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as MetriportApi from "../../../../api";
import * as core from "../../../../core";

export const Duration: core.serialization.ObjectSchema<serializers.fhir.Duration.Raw, MetriportApi.fhir.Duration> =
    core.serialization.object({
        id: core.serialization.string().optional(),
        extension: core.serialization
            .list(core.serialization.lazyObject(async () => (await import("../../..")).fhir.Extension))
            .optional(),
        value: core.serialization.lazy(async () => (await import("../../..")).fhir.Decimal).optional(),
        comparator: core.serialization.lazy(async () => (await import("../../..")).fhir.DurationComparator).optional(),
        unit: core.serialization.string().optional(),
        system: core.serialization.lazy(async () => (await import("../../..")).fhir.Uri).optional(),
        code: core.serialization.lazy(async () => (await import("../../..")).fhir.Code).optional(),
    });

export declare namespace Duration {
    interface Raw {
        id?: string | null;
        extension?: serializers.fhir.Extension.Raw[] | null;
        value?: serializers.fhir.Decimal.Raw | null;
        comparator?: serializers.fhir.DurationComparator.Raw | null;
        unit?: string | null;
        system?: serializers.fhir.Uri.Raw | null;
        code?: serializers.fhir.Code.Raw | null;
    }
}
