/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as MetriportApi from "../../../../api";
import * as core from "../../../../core";

export const HumanNameUse: core.serialization.Schema<
    serializers.fhir.HumanNameUse.Raw,
    MetriportApi.fhir.HumanNameUse
> = core.serialization.enum_(["usual", "official", "temp", "nickname", "anonymous", "old", "maiden"]);

export declare namespace HumanNameUse {
    type Raw = "usual" | "official" | "temp" | "nickname" | "anonymous" | "old" | "maiden";
}
