/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as MetriportApi from "../../../../api";
import * as core from "../../../../core";

export const Instant: core.serialization.Schema<serializers.fhir.Instant.Raw, MetriportApi.fhir.Instant> =
    core.serialization.string();

export declare namespace Instant {
    type Raw = string;
}
