/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as MetriportApi from "../../../../api";
import * as core from "../../../../core";

export const TriggerDefinition: core.serialization.ObjectSchema<
    serializers.fhir.TriggerDefinition.Raw,
    MetriportApi.fhir.TriggerDefinition
> = core.serialization.object({
    id: core.serialization.string().optional(),
    extension: core.serialization
        .list(core.serialization.lazyObject(async () => (await import("../../..")).fhir.Extension))
        .optional(),
    type: core.serialization.lazy(async () => (await import("../../..")).fhir.TriggerDefinitionType).optional(),
    name: core.serialization.string().optional(),
    timingTiming: core.serialization.lazyObject(async () => (await import("../../..")).fhir.Timing).optional(),
    timingReference: core.serialization.lazyObject(async () => (await import("../../..")).fhir.Reference).optional(),
    timingDate: core.serialization.string().optional(),
    timingDateTime: core.serialization.string().optional(),
    data: core.serialization
        .list(core.serialization.lazyObject(async () => (await import("../../..")).fhir.DataRequirement))
        .optional(),
    condition: core.serialization.lazyObject(async () => (await import("../../..")).fhir.Expression).optional(),
});

export declare namespace TriggerDefinition {
    interface Raw {
        id?: string | null;
        extension?: serializers.fhir.Extension.Raw[] | null;
        type?: serializers.fhir.TriggerDefinitionType.Raw | null;
        name?: string | null;
        timingTiming?: serializers.fhir.Timing.Raw | null;
        timingReference?: serializers.fhir.Reference.Raw | null;
        timingDate?: string | null;
        timingDateTime?: string | null;
        data?: serializers.fhir.DataRequirement.Raw[] | null;
        condition?: serializers.fhir.Expression.Raw | null;
    }
}
