/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as MetriportApi from "../../../../api";
import * as core from "../../../../core";

export const TriggerDefinitionType: core.serialization.Schema<
    serializers.fhir.TriggerDefinitionType.Raw,
    MetriportApi.fhir.TriggerDefinitionType
> = core.serialization.enum_([
    "named-event",
    "periodic",
    "data-changed",
    "data-added",
    "data-modified",
    "data-removed",
    "data-accessed",
    "data-access-ended",
]);

export declare namespace TriggerDefinitionType {
    type Raw =
        | "named-event"
        | "periodic"
        | "data-changed"
        | "data-added"
        | "data-modified"
        | "data-removed"
        | "data-accessed"
        | "data-access-ended";
}
