/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as MetriportApi from "../../../../api";
import * as core from "../../../../core";

export const Url: core.serialization.Schema<serializers.fhir.Url.Raw, MetriportApi.fhir.Url> =
    core.serialization.string();

export declare namespace Url {
    type Raw = string;
}
