/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Metriport from "../../..";

/**
 * @example
 *     {
 *         addressLine1: "2261 Market Street",
 *         addressLine2: "#4818",
 *         city: "San Francisco",
 *         state: Metriport.UsState.Ca,
 *         zip: "94114",
 *         country: "USA"
 *     }
 */
export interface Address {
    /** The address. */
    addressLine1: string;
    /** The address details, for example `#4451` */
    addressLine2?: string;
    /** The city. */
    city: string;
    /** The 2 letter state acronym, for example `CA` */
    state: Metriport.UsState;
    /** Zip must be a string consisting of 5 numbers. */
    zip: string;
    /** Defaults to “USA” */
    country: string;
}
